"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { demoBatches, engineeringRule, machines, productionLines } from "../../lib/mock-data";
import { calculateFaultTrends, defectCounts, statusCounts } from "../../lib/calculations";
import { mechanicalKnowledge } from "../../lib/mechanical-knowledge";
import { uploadAndInspectImage, type InspectApiResponse } from "../../lib/api";
import type { Disposition, DefectClass, Inspection, InspectionUploadLog, InspectorReview, ProductionLine, Severity } from "../../lib/types";

type ViewName = "Plant Overview" | "AI Inspection Studio" | "Batch Quality Analytics" | "Fault Intelligence Board" | "Human Review" | "Inspection Log";
type Props = { view: ViewName; inspections: Inspection[]; uploadLogs: InspectionUploadLog[]; selectedPart: string; setSelectedPart: (id: string) => void; navigate: (view: ViewName, partId?: string) => void; saveReview: (id: string, review: InspectorReview) => void; backendOnline: boolean; inferenceMode: string; onInspectionCreated: (row: Inspection, response: InspectApiResponse) => void };
const classes: DefectClass[] = ["Surface Crack", "Scratch", "Scoring", "Pitting", "Inclusion", "Casting Defect", "Machining Defect", "Chipping / edge damage", "Unknown Anomaly"];
const dispositions: Disposition[] = ["PASS", "REVIEW", "REJECT"];

function mapBackendClass(value: string): DefectClass {
  const normalized = value.toLowerCase();
  if (normalized.includes("crack")) return "Surface Crack";
  if (normalized.includes("scoring") || normalized.includes("grooving")) return "Scoring";
  if (normalized.includes("pitting") || normalized.includes("cavitation") || normalized.includes("corrosion")) return "Pitting";
  if (normalized.includes("inclusion")) return "Inclusion";
  if (normalized.includes("flange") || normalized.includes("distortion")) return "Machining Defect";
  if (normalized.includes("unknown")) return "Unknown Anomaly";
  return "Unknown Anomaly";
}

function mapBackendSeverity(value: string): Severity {
  const normalized = value.toLowerCase();
  return normalized === "critical" ? "Critical" : normalized === "high" ? "High" : normalized === "medium" ? "Medium" : "Low";
}

function simpleFindingDescription(type: string): string {
  if (/crack/i.test(type)) return "A crack is a break in the brake disc. It may spread as the part heats and cools.";
  if (/scor|groov/i.test(type)) return "A groove or deep scratch was found where the brake pad touches the disc.";
  if (/pit|corros/i.test(type)) return "Small pits or corroded spots were found on the part.";
  if (/scratch/i.test(type)) return "A surface mark was found and may need a closer look.";
  return `${type} was found in the marked area. A quality reviewer should confirm it.`;
}

function simpleRecommendation(value: string | undefined, fallback: string): string {
  if (!value) return fallback;
  if (/condemn rotor|immediate replacement/i.test(value)) return "Do not use this rotor. Replace it, then ask a mechanic to check the brake caliper.";
  return value;
}

function mapBackendInspection(result: InspectApiResponse, file: File): Inspection {
  const first = result.detections[0];
  const defect = first ? mapBackendClass(first.defect_type) : "None detected";
  const severity = first ? result.detections.map((item) => mapBackendSeverity(item.severity)).sort((a, b) => ["None", "Low", "Medium", "High", "Critical"].indexOf(b) - ["None", "Low", "Medium", "High", "Critical"].indexOf(a))[0] : "None";
  const assessmentSeverity: Severity = first ? severity as Severity : "Low";
  const mechanicalExplanation = first ? {
    defectClass: mapBackendClass(first.defect_type),
    whatItIs: `${first.defect_type} identified in the uploaded component image.`,
    principle: first.explanation || result.summary_message,
    possibleContributors: [],
    potentialEffect: `Backend condition assessment: ${result.condition_classification.condition}. ${result.condition_classification.triage_verdict}`,
    suggestedAction: first.recommendation || "Review the backend result with a qualified quality engineer.",
  } : undefined;
  return {
    id: result.image_id,
    batchId: "Not linked",
    model: file.name,
    line: "Line 01 · High-speed",
    machine: "Not linked",
    station: "Backend inspection",
    time: new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date()),
    defect,
    severity,
    status: result.overall_status,
    confidence: first?.confidence ?? result.condition_classification.confidence,
    detections: result.detections.map((item, index) => ({ id: `${result.image_id}-${index + 1}`, className: mapBackendClass(item.defect_type), confidence: item.confidence, region: item.location || "Component surface", bbox: item.bbox, severity: mapBackendSeverity(item.severity) })),
    mechanicalExplanation,
    assessment: { severity: assessmentSeverity, disposition: result.overall_status, ruleId: result.model_name, ruleDescription: result.summary_message, defectAreaRatioPercent: first?.area_percentage, provisional: true },
  };
}

function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: string }) { return <span className={`aa-badge ${tone}`}>{children}</span>; }
function Header({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="aa-page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/>{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{action && <div className="aa-page-actions">{action}</div>}</div>; }
function MiniStat({ title, value, caption, tone = "blue" }: { title: string; value: string; caption: string; tone?: string }) { return <article className="stat-card aa-mini-stat"><div className="stat-top"><span>{title}</span><span className={`stat-icon ${tone}`}/></div><div className="stat-value">{value}</div><div className="stat-foot">{caption}</div></article>; }
function downloadCsv(text: string, name: string) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/csv;charset=utf-8" })); link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(link.href), 1000); }

function LiveImageComparison({ source, result, selectedIndex, onSelect, zoom, annotatedSource }: { source: string; result: InspectApiResponse; selectedIndex: number; onSelect: (index: number) => void; zoom: number; annotatedSource: string }) {
  const [showBoxes, setShowBoxes] = useState(true);
  const [showBackendRaster, setShowBackendRaster] = useState(false);
  const colors = (type: string) => /crack/i.test(type) ? "#ed4545" : /scor|groov/i.test(type) ? "#ef9b32" : /pit|corros/i.test(type) ? "#a855d8" : "#3478e5";
  const image = (withOverlay: boolean) => <div className="aa-live-stage">
    <div className="aa-live-canvas" style={{ transform: `scale(${zoom})` }}>
      <Image unoptimized width={1200} height={1200} src={withOverlay && showBackendRaster && annotatedSource ? annotatedSource : source} alt={withOverlay && showBackendRaster && annotatedSource ? "Backend annotated inspection image" : "Original uploaded component"}/>
      {withOverlay && showBoxes && <svg className="aa-live-overlay" viewBox={`0 0 ${result.image_width} ${result.image_height}`} preserveAspectRatio="xMidYMid meet" role="img" aria-label={`${result.detections.length} YOLO detections over original image`}>
        {result.detections.map((d, index) => {
          const [x1, y1, x2, y2] = d.bbox; const color = colors(d.defect_type); const label = `#${index + 1} ${d.defect_type} ${(d.confidence * 100).toFixed(0)}%`;
          return <g key={`${d.defect_type}-${index}`} role="button" tabIndex={0} aria-label={`Select ${label}`} onClick={() => onSelect(index)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(index); } }} style={{ cursor: "pointer" }}>
            {d.mask_polygon && d.mask_polygon.length >= 3 && <polygon points={d.mask_polygon.map(([x, y]) => `${x},${y}`).join(" ")} fill={color} fillOpacity={index === selectedIndex ? ".26" : ".14"} stroke={color} strokeWidth={Math.max(result.image_width, result.image_height) / 500} vectorEffect="non-scaling-stroke"/>}
            <rect x={x1} y={y1} width={x2 - x1} height={y2 - y1} fill="none" stroke={color} strokeWidth={Math.max(result.image_width, result.image_height) / (index === selectedIndex ? 180 : 300)} vectorEffect="non-scaling-stroke" className={index === selectedIndex ? "aa-live-box selected" : "aa-live-box"}/>
            <rect x={x1} y={Math.max(0, y1 - Math.max(result.image_height * .035, 22))} width={Math.min(x2 - x1, result.image_width * .48)} height={Math.max(result.image_height * .035, 22)} rx={4} fill={color}/>
            <text x={x1 + 6} y={Math.max(15, y1 - Math.max(result.image_height * .035, 22) / 2 + 4)} fill="white" fontSize={Math.max(result.image_width * .014, 12)} fontWeight="700">{label}</text>
          </g>;
        })}
      </svg>}
    </div>
  </div>;
  return <div className="aa-live-comparison">
    <section className="aa-compare-card"><div className="aa-compare-head"><b>ORIGINAL IMAGE</b><span>{result.image_width} × {result.image_height}px</span></div>{image(false)}</section>
    <section className="aa-compare-card"><div className="aa-compare-head"><b>YOLO MARKED IMAGE</b><span>{result.detections.length} areas marked</span></div>{image(true)}</section>
    <div className="aa-live-controls"><label><input type="checkbox" checked={showBoxes} onChange={(e) => setShowBoxes(e.target.checked)}/> Show marked areas</label>{annotatedSource && <label><input type="checkbox" checked={showBackendRaster} onChange={(e) => setShowBackendRaster(e.target.checked)}/> Show YOLO image</label>}</div>
    <details className="aa-live-results"><summary className="aa-live-results-head"><b>Image findings</b><span>{result.detections.length} · select to highlight ⌄</span></summary>{result.detections.length ? result.detections.map((d, index) => <button key={`${d.defect_type}-${index}`} className={`aa-live-detection ${selectedIndex === index ? "active" : ""}`} onClick={() => onSelect(index)}><span className="aa-live-number" style={{ background: colors(d.defect_type) }}>{index + 1}</span><span className="aa-live-detection-main"><b>{d.defect_type}</b><small>{d.location || "Location not provided"} · {(d.confidence * 100).toFixed(1)}% match · {d.severity} severity</small></span><span>↗</span></button>) : <p className="aa-muted">YOLO found no defects in this image.</p>}</details>
  </div>;
}

function LiveInspectionAnalysis({ result, selectedIndex, onSelect, navigate }: { result: InspectApiResponse; selectedIndex: number; onSelect: (index: number) => void; navigate: Props["navigate"] }) {
  const detection = result.detections[selectedIndex];
  const defectClass = detection ? mapBackendClass(detection.defect_type) : null;
  const supportedExplanation = defectClass && defectClass !== "Unknown Anomaly" ? mechanicalKnowledge[defectClass] : null;
  const recommendation = simpleRecommendation(detection?.recommendation?.trim() || supportedExplanation?.suggestedAction, detection ? "Ask a quality reviewer to check this marked area." : "No defects were found, but this check alone cannot confirm the part is safe.");
  const statusTone = result.overall_status === "PASS" ? "passed" : result.overall_status === "REJECT" ? "reject" : "review";
  const plainSummary = result.defect_count ? `${result.defect_count} possible issue${result.defect_count === 1 ? "" : "s"} found. Review the marked image below.` : "No visible issue found. This check cannot guarantee the part is safe.";
  return <section className="panel aa-live-analysis">
    <div className="panel-heading"><div><h2>Inspection result</h2><p>Review the marked image and key findings</p></div><Badge tone={result.inference_mode === "real_ai" ? "passed" : "neutral"}>{result.inference_mode === "real_ai" ? "REAL YOLO AI" : "MOCK"}</Badge></div>
    <div className="aa-analysis-meta">
      <div><small>PART</small><b>{result.brake_component_type || "Brake component"}</b></div>
      <div><small>RESULT</small><Badge tone={statusTone}>{result.overall_status}{result.overall_status === "REJECT" ? " · do not use" : result.overall_status === "REVIEW" ? " · check again" : " · passed"}</Badge></div>
      <div><small>CONDITION</small><b>{result.condition_classification.condition} · {(result.condition_classification.confidence * 100).toFixed(0)}% sure</b></div>
      <div><small>WEAR SCORE</small><b>{result.condition_classification.wear_index_score.toFixed(1)} / 100</b></div>
      <div><small>ISSUES FOUND</small><b>{result.defect_count}</b></div>
    </div>
    <div className="aa-analysis-status"><b>{plainSummary}</b></div>
    <details className="aa-detail-dropdown"><summary><span>Findings</span><b>{result.detections.length ? result.detections.map((d) => `${d.defect_type} · ${d.severity}`).join(", ") : "No visible issues"}</b><span className="aa-dropdown-chevron">⌄</span></summary>
      {result.detections.length ? <div className="aa-analysis-detection-list">{result.detections.map((d, index) => <button key={`${d.defect_type}-${index}`} className={`aa-analysis-detection ${selectedIndex === index ? "active" : ""}`} onClick={() => onSelect(index)}><span className="aa-live-number" style={{ background: /crack/i.test(d.defect_type) ? "#ed4545" : /scor|groov/i.test(d.defect_type) ? "#ef9b32" : /pit|corros/i.test(d.defect_type) ? "#a855d8" : "#3478e5" }}>{index + 1}</span><span><b>{d.defect_type}</b><small>{d.location || "See marked area"} · {(d.confidence * 100).toFixed(1)}% match</small></span><Badge tone={d.severity === "critical" || d.severity === "high" ? "failed" : d.severity === "medium" ? "review" : "neutral"}>{d.severity.toUpperCase()}</Badge></button>)}</div> : <p className="aa-muted">This check cannot guarantee that the part is safe.</p>}
    </details>
    <details className="aa-detail-dropdown"><summary><span>Why it was flagged</span><b>{detection ? simpleFindingDescription(detection.defect_type) : "No issue was marked"}</b><span className="aa-dropdown-chevron">⌄</span></summary><div className="aa-detail-dropdown-content"><p>{detection?.mask_polygon?.length ? "The colored outline shows the area YOLO identified." : detection ? "The box shows where YOLO identified the possible issue." : "No visible issue was found in the uploaded image."}</p>{detection?.explanation && <p><b>Model explanation:</b> {detection.explanation}</p>}</div></details>
    <details className="aa-detail-dropdown"><summary><span>What to do next</span><b>{recommendation}</b><span className="aa-dropdown-chevron">⌄</span></summary><div className="aa-detail-dropdown-content"><p>{recommendation}</p><p>The image cannot identify the cause or machine. Ask a quality reviewer before making a final decision.</p>{detection?.recommendation && <p><b>Backend recommendation:</b> {detection.recommendation}</p>}</div></details>
    <details className="aa-detail-dropdown"><summary><span>Technical details</span><b>{result.model_name} · {result.defect_count} findings</b><span className="aa-dropdown-chevron">⌄</span></summary><div className="aa-technical-details"><div><small>Inspection ID</small><b>{result.image_id}</b></div><div><small>Model</small><b>{result.model_name}</b></div><div><small>Inference</small><b>{result.inference_mode}</b></div><div><small>Condition confidence</small><b>{(result.condition_classification.confidence * 100).toFixed(1)}%</b></div><div><small>Wear index</small><b>{result.condition_classification.wear_index_score.toFixed(1)} / 100</b></div><div><small>Condition guidance</small><b>{result.condition_classification.triage_verdict}</b></div><div className="aa-technical-detection"><small>Backend summary</small><b>{result.summary_message}</b></div>{result.detections.map((d, index) => <div className="aa-technical-detection" key={`technical-${index}`}><b>{d.defect_type} · {(d.confidence * 100).toFixed(1)}% · {d.severity}</b><span>Location: {d.location || "Not provided"}</span><span>Image coordinates: {d.bbox.map((value) => value.toFixed(1)).join(", ")} px</span><span>Bounding box covers {d.area_percentage.toFixed(2)}% of the image; this is not the physical defect area.</span>{d.mask_polygon?.length ? <span>Segmentation outline: {d.mask_polygon.length} points</span> : null}<span>Physical crack length, critical zone check, and engineering rule violations: not returned by this inspection.</span></div>)}<div className="aa-technical-detection"><small>Root cause</small><b>Not identified from the image. No machine or process data was linked to this inspection.</b></div></div></details>
    <div className="aa-analysis-actions"><button className="button button-secondary" onClick={() => navigate("Plant Overview")}>Plant overview</button><button className="button button-primary" onClick={() => navigate("Human Review", result.image_id)}>Ask for human review</button></div>
  </section>;
}

export function AutoAuditView(props: Props) {
  if (props.view === "AI Inspection Studio") return <Inspector {...props}/>;
  if (props.view === "Batch Quality Analytics") return <BatchAnalytics {...props}/>;
  if (props.view === "Fault Intelligence Board") return <MachineIntelligence {...props}/>;
  if (props.view === "Human Review") return <HumanReview {...props}/>;
  if (props.view === "Inspection Log") return <InspectionLog {...props}/>;
  return <Overview {...props}/>;
}

function InspectionLog({ uploadLogs }: Props) {
  return <>
    <Header eyebrow="UPLOAD HISTORY" title="Inspection Log" subtitle="Your uploaded images and their saved inspection results" action={<Badge tone="neutral">{uploadLogs.length} uploads</Badge>}/>
    {uploadLogs.length ? <section className="panel aa-upload-log">
      {uploadLogs.map((entry) => <details className="aa-upload-log-entry" key={entry.id}>
        <summary><span className="aa-upload-log-name"><b>{entry.fileName}</b><small>{entry.component} · {new Date(entry.uploadedAt).toLocaleString()}</small></span><Badge tone={entry.result === "PASS" ? "passed" : entry.result === "REJECT" ? "reject" : "review"}>{entry.result}</Badge><span className="aa-upload-log-count">{entry.defectCount} finding{entry.defectCount === 1 ? "" : "s"}</span><span className="aa-dropdown-chevron">⌄</span></summary>
        <div className="aa-upload-log-body">
          <p>{entry.summary}</p>
          <div className="aa-upload-log-metrics"><span>Condition <b>{entry.condition} · {(entry.conditionConfidence * 100).toFixed(1)}%</b></span><span>Wear score <b>{entry.wearIndex.toFixed(1)} / 100</b></span><span>YOLO model <b>{entry.modelName}</b></span><span>Mode <b>{entry.inferenceMode === "real_ai" ? "Real YOLO" : "Mock"}</b></span></div>
          {entry.detections.map((detection, index) => <details className="aa-upload-log-detection" key={`${entry.id}-${index}`}><summary>{detection.defectType} · {(detection.confidence * 100).toFixed(1)}% · {detection.severity}</summary><div className="aa-technical-details"><div><small>Location</small><b>{detection.location || "Not provided"}</b></div><div><small>Image coordinates</small><b>{detection.bbox.map((value) => value.toFixed(1)).join(", ")} px</b></div><div><small>Bounding-box area</small><b>{detection.areaPercentage.toFixed(2)}% of image</b></div>{detection.maskPolygon?.length ? <div><small>Segmentation outline</small><b>{detection.maskPolygon.length} points</b></div> : null}{detection.explanation ? <div><small>Explanation</small><b>{detection.explanation}</b></div> : null}{detection.recommendation ? <div><small>Suggested action</small><b>{detection.recommendation}</b></div> : null}</div></details>)}
          <details className="aa-upload-log-detection"><summary>All technical details</summary><div className="aa-technical-details"><div><small>Inspection ID</small><b>{entry.id}</b></div><div><small>Summary from model</small><b>{entry.summary}</b></div></div></details>
        </div>
      </details>)}
    </section> : <div className="panel aa-upload-log-empty"><b>No uploads yet</b><span>When you inspect an image in AI Inspection Studio, it will appear here with its results.</span></div>}
  </>;
}

function Overview({ inspections, navigate, setSelectedPart }: Props) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("All"); const [severity, setSeverity] = useState("All"); const [line, setLine] = useState("All lines"); const [range, setRange] = useState("24 hours"); const [page, setPage] = useState(1);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("line"); if (requested && productionLines.some((item) => item.id === requested)) setLine(requested); }, []);
  const filtered = inspections.filter((item) => (item.id.toLowerCase().includes(search.toLowerCase())) && (status === "All" || item.status === status) && (severity === "All" || item.severity === severity) && (line === "All lines" || item.line.startsWith(line)));
  const perPage = 5; const pages = Math.max(1, Math.ceil(filtered.length / perPage)); const pageRows = filtered.slice((page - 1) * perPage, page * perPage);
  const lines: ProductionLine[] = productionLines;
  const open = (id: string) => { setSelectedPart(id); navigate("AI Inspection Studio", id); };
  const csv = `Part ID,Batch ID,Line,Time,Defect,Severity,Result\n${filtered.map((r) => [r.id, r.batchId, r.line, r.time, r.review?.finalClass ?? r.defect, r.severity, r.review?.finalDisposition ?? r.status].join(",")).join("\n")}`;
  return <>
    <Header eyebrow="PLANT OVERVIEW" title="Plant Overview" subtitle="Real-time production quality and inspection intelligence" action={<><label className="aa-select-label">Plant North · 01<select aria-label="Production line filter" value={line} onChange={(e) => { setLine(e.target.value); setPage(1); const url = new URL(window.location.href); if (e.target.value === "All lines") url.searchParams.delete("line"); else url.searchParams.set("line", e.target.value); window.history.replaceState({}, "", url); }}><option>All lines</option><option>Line 01</option><option>Line 02</option><option>Line 03</option></select></label><select className="aa-select" value={range} onChange={(e) => setRange(e.target.value)} aria-label="Date range"><option>24 hours</option><option>7 days</option></select><Badge tone="demo">DEMO DATA</Badge><button className="button button-secondary" onClick={() => window.location.reload()}>↻ Refresh</button></>}/>
    <div className="stat-grid"><MiniStat title="INSPECTED PARTS" value="2,481" caption="Plant-level demo aggregate · 24h"/><MiniStat title="FIRST-PASS YIELD" value="98.6%" caption="Plant-level demo aggregate" tone="green"/><MiniStat title="NEEDS REVIEW" value="18" caption="Plant-level demo aggregate" tone="amber"/><MiniStat title="LINE AVAILABILITY" value="94.2%" caption="Plant-level demo aggregate" tone="violet"/></div>
    <div className="middle-grid"><section className="panel yield-panel"><div className="panel-heading"><div><h2>Production quality trend</h2><p>First-pass yield · illustrative demo series</p></div><select className="aa-select" value={range} onChange={(e) => setRange(e.target.value)}><option>24 hours</option><option>7 days</option></select></div><div className="aa-chart"><div className="aa-chart-axis"><span>100%</span><span>99%</span><span>98%</span><span>97%</span></div><svg viewBox="0 0 640 190" preserveAspectRatio="none" role="img" aria-label={`Illustrative first-pass yield over ${range}`}><title>Illustrative demo series · no live production measurements</title><path className="aa-chart-fill" d={range === "24 hours" ? "M0 145 C65 130 76 115 125 126 S204 82 259 97 S335 57 390 68 S465 36 512 49 S590 20 640 28 V190 H0Z" : "M0 153 C70 141 82 120 135 130 S208 99 260 112 S344 72 395 86 S468 53 523 62 S588 35 640 43 V190 H0Z"}/><path className="aa-chart-line" d={range === "24 hours" ? "M0 145 C65 130 76 115 125 126 S204 82 259 97 S335 57 390 68 S465 36 512 49 S590 20 640 28" : "M0 153 C70 141 82 120 135 130 S208 99 260 112 S344 72 395 86 S468 53 523 62 S588 35 640 43"}><title>Demo yield trend</title></path></svg><div className="aa-chart-labels"><span>{range === "24 hours" ? "06:00" : "Day 1"}</span><span>{range === "24 hours" ? "10:00" : "Day 2"}</span><span>{range === "24 hours" ? "14:00" : "Day 3"}</span><span>{range === "24 hours" ? "18:00" : "Day 4"}</span><span>{range === "24 hours" ? "22:00" : "Day 5"}</span></div></div></section>
      <section className="panel lines-panel"><div className="panel-heading"><div><h2>Production lines</h2><p>Current quality and output</p></div></div><div className="aa-overview-lines">{lines.map((item) => <button className="aa-overview-line" key={item.id} onClick={() => { setLine(item.id); setPage(1); const url = new URL(window.location.href); url.searchParams.set("line", item.id); window.history.replaceState({}, "", url); }}><span className="line-number blue">{item.id.slice(-2)}</span><span className="line-detail"><b>{item.id} — {item.name}</b><small>{item.inspected.toLocaleString()} inspected · {item.yield}% yield</small></span><Badge tone={item.status === "Operational" ? "passed" : "review"}>{item.status}</Badge></button>)}</div></section></div>
    <section className="panel inspections-panel"><div className="panel-heading inspection-heading"><div><h2>Recent inspections</h2><p>Open a component to see the complete engineering and process story</p></div><div className="inspection-actions"><label className="table-search"><span>⌕</span><input aria-label="Search part ID" placeholder="Search Part ID" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}/></label><select className="aa-select" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option>All</option>{dispositions.map((s) => <option key={s}>{s}</option>)}</select><select className="aa-select" value={severity} onChange={(e) => { setSeverity(e.target.value); setPage(1); }}><option>All</option>{["Critical", "High", "Medium", "Low", "None"].map((s) => <option key={s}>{s}</option>)}</select><button className="button button-secondary small-button" onClick={() => downloadCsv(csv, "autoaudit-inspections.csv")}>↓ Export</button></div></div><InspectionTable rows={pageRows} open={open}/><div className="table-footer"><span>Showing {filtered.length ? (page - 1) * perPage + 1 : 0}–{Math.min(page * perPage, filtered.length)} of {filtered.length} demo inspection records</span><span className="aa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><b>{page} / {pages}</b><button disabled={page >= pages} onClick={() => setPage(page + 1)}>Next</button></span></div></section>
  </>;
}

function InspectionTable({ rows, open }: { rows: Inspection[]; open: (id: string) => void }) {
  if (!rows.length) return <div className="empty-state">No inspections match these filters.</div>;
  return <div className="table-scroll"><table><thead><tr><th>PART / BATCH</th><th>PRODUCTION LINE</th><th>TIME</th><th>DEFECT CLASS</th><th>SEVERITY</th><th>RESULT</th><th/></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="part-id"><span className="part-glyph">◉</span><span><b>{row.id}</b><small>{row.batchId}</small></span></div></td><td>{row.line}</td><td className="mono">{row.time}</td><td>{row.review?.finalClass ?? row.defect}</td><td><Badge tone={row.severity === "Critical" || row.severity === "High" ? "failed" : row.severity === "Medium" ? "review" : "neutral"}>{row.severity}</Badge></td><td><Badge tone={row.status.toLowerCase()}>{row.review?.finalDisposition ?? row.status}</Badge></td><td><button className="text-link" onClick={() => open(row.id)}>Inspect image →</button></td></tr>)}</tbody></table></div>;
}

function RotorIllustration({ zoom, overlays, selectedDetection, detections, opacity }: { zoom: number; overlays: Record<string, boolean>; selectedDetection: string; detections: Inspection["detections"]; opacity: number }) {
  return <div className="aa-rotor-stage"><svg viewBox="0 0 640 440" role="img" aria-label="Illustrative brake disc inspection image with demonstration annotations" style={{ transform: `scale(${zoom})` }}>
    <defs><radialGradient id="rotor-metal"><stop offset="0" stopColor="#dce1e6"/><stop offset=".42" stopColor="#929ca6"/><stop offset=".58" stopColor="#e5e8ea"/><stop offset=".76" stopColor="#aab2b9"/><stop offset=".88" stopColor="#d8dde0"/><stop offset="1" stopColor="#727d86"/></radialGradient><radialGradient id="hub-metal"><stop offset="0" stopColor="#7f8992"/><stop offset=".7" stopColor="#c5cbd0"/><stop offset="1" stopColor="#737d86"/></radialGradient><filter id="shadow"><feGaussianBlur stdDeviation="8"/></filter><radialGradient id="heat"><stop stopColor="#ef5550" stopOpacity=".58"/><stop offset=".5" stopColor="#f4bd56" stopOpacity=".32"/><stop offset="1" stopColor="#f4bd56" stopOpacity="0"/></radialGradient></defs>
    <ellipse cx="320" cy="228" rx="226" ry="195" fill="#334256" opacity=".16" filter="url(#shadow)"/><g transform="rotate(-8 320 220)"><circle cx="320" cy="216" r="183" fill="url(#rotor-metal)" stroke="#697680" strokeWidth="3"/><circle cx="320" cy="216" r="155" fill="#69757e" stroke="#edf0f2" strokeWidth="2"/><circle cx="320" cy="216" r="138" fill="url(#rotor-metal)" stroke="#56636d" strokeWidth="2"/><circle cx="320" cy="216" r="92" fill="url(#hub-metal)" stroke="#59646e" strokeWidth="3"/><circle cx="320" cy="216" r="49" fill="#8e989f" stroke="#dfe3e6" strokeWidth="4"/><circle cx="320" cy="216" r="22" fill="#38434d" stroke="#d5dadd" strokeWidth="4"/>
    {Array.from({ length: 10 }, (_, i) => <g key={i} transform={`rotate(${i * 36} 320 216)`}><ellipse cx="320" cy="75" rx="7" ry="18" fill="#63707a" stroke="#e6e9ea" strokeWidth="2"/><ellipse cx="320" cy="118" rx="4" ry="10" fill="#515d67" opacity=".75"/><circle cx="320" cy="156" r="7" fill="#46515b" stroke="#e2e5e7" strokeWidth="2"/></g>)}
    <path d="M437 130 l-12 10 9 6 -16 13 4 10 -13 13 3 10" fill="none" stroke="#672d2b" strokeWidth="7" strokeLinecap="round" opacity=".88"/><path d="M437 130 l-12 10 9 6 -16 13 4 10 -13 13 3 10" fill="none" stroke="#d75d52" strokeWidth="3" strokeLinecap="round"/>
    {overlays.heatmap && <ellipse cx="420" cy="160" rx="92" ry="65" fill="url(#heat)" opacity={opacity}/>}
    {overlays.masks && <path d="M403 137 Q427 118 447 139 L439 157 427 164 432 180 413 197 406 177 414 161Z" fill="#eb6260" opacity={opacity * .46} stroke="#c64e49" strokeWidth="2"/>}
    {overlays.boxes && detections.map((d) => <g key={d.id} className={selectedDetection === d.id ? "is-selected" : ""}><rect x={d.bbox[0]} y={d.bbox[1]} width={d.bbox[2] - d.bbox[0]} height={d.bbox[3] - d.bbox[1]} fill="#e9544b" fillOpacity=".07" stroke="#d94e45" strokeWidth="3" strokeDasharray={selectedDetection === d.id ? "0" : "7 4"}/><rect x={d.bbox[0]} y={d.bbox[1] - 23} width="118" height="20" rx="4" fill="#263548"/><text x={d.bbox[0] + 7} y={d.bbox[1] - 9} fill="white" fontSize="10" fontWeight="600">{d.className} · {(d.confidence * 100).toFixed(0)}%</text></g>)}
    </g></svg><div className="aa-image-caption"><span>SVG illustration · demo annotations</span><span>Image-space only · no scale calibration</span></div></div>;
}

function Inspector({ inspections, selectedPart, setSelectedPart, navigate, backendOnline, inferenceMode, onInspectionCreated }: Props) {
  const item = inspections.find((r) => r.id === selectedPart) ?? inspections[0]; const [selectedDetection, setSelectedDetection] = useState(item.detections[0]?.id ?? ""); const [boxes, setBoxes] = useState(true); const [masks, setMasks] = useState(false); const [heatmap, setHeatmap] = useState(false); const [opacity, setOpacity] = useState(.65); const [zoom, setZoom] = useState(1); const [full, setFull] = useState(false);
  const selectableInspections = inspections.filter((row) => row.status !== "PASS" || /^BD-\d{4}$/.test(row.id) || row.id === selectedPart);
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [annotatedPreview, setAnnotatedPreview] = useState(""); const [fileMessage, setFileMessage] = useState(""); const [uploadError, setUploadError] = useState(""); const [scanning, setScanning] = useState(false); const [liveResult, setLiveResult] = useState<InspectApiResponse | null>(null); const inputRef = useRef<HTMLInputElement>(null); const [demoLoaded, setDemoLoaded] = useState(true); const [liveSelection, setLiveSelection] = useState(0);
  const startingPartRef = useRef(selectedPart);
  useEffect(() => { if (!file) { setPreview(""); return; } const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url); }, [file]);
  const inspectFile = async (next: File) => {
    setFile(next); setAnnotatedPreview(""); setLiveResult(null); setDemoLoaded(false); setUploadError(""); setFileMessage(""); setLiveSelection(0);
    setScanning(true); setFileMessage("Running YOLOv8 Inspection...");
    try {
      const response = await uploadAndInspectImage(next);
      if (response.status === "failed") throw new Error(response.summary_message || "The backend could not inspect this image.");
      const record = mapBackendInspection(response, next);
      setLiveResult(response);
      if (response.annotated_image_base64) setAnnotatedPreview(response.annotated_image_base64.startsWith("data:") ? response.annotated_image_base64 : `data:image/jpeg;base64,${response.annotated_image_base64}`);
      onInspectionCreated(record, response);
      setFileMessage(response.defect_count ? `Check complete · ${response.defect_count} finding${response.defect_count === 1 ? "" : "s"} marked.` : "Check complete · no visible issues found.");
    } catch (error) {
      setUploadError(`${!backendOnline ? "Backend offline on :8000 — operating in local demonstration mode." : error instanceof Error ? error.message : "Inspection request failed."} No detections were fabricated; the uploaded image remains available as a preview.`);
      setFileMessage("Inspection unavailable · preview only.");
    } finally { setScanning(false); }
  };
  const chooseFile = (next: File | undefined) => { if (!next) return; if (!["image/png", "image/jpeg", "image/webp"].includes(next.type) || next.size > 15 * 1024 * 1024) { setFileMessage("Choose a JPG, PNG, or WEBP image under 15 MB."); return; } void inspectFile(next); };
  const clearUpload = () => { setFile(null); setAnnotatedPreview(""); setLiveResult(null); setLiveSelection(0); setDemoLoaded(true); setUploadError(""); setFileMessage("Upload a brake component image to run YOLO."); if (inputRef.current) inputRef.current.value = ""; setSelectedPart(startingPartRef.current); };
  const loadSample = async (name: "crack" | "clean" | "surface_defect") => {
    setUploadError(""); setFileMessage("Loading backend sample...");
    try {
      const response = await fetch(`/api/py/sample/${name}`);
      if (!response.ok) throw new Error(`Sample image unavailable (${response.status}).`);
      const blob = await response.blob();
      const sample = new File([blob], `autoaudit-sample-${name}.jpg`, { type: blob.type || "image/jpeg" });
      await inspectFile(sample);
    } catch (error) { setUploadError(`${error instanceof Error ? error.message : "Could not load sample."} Check that the FastAPI backend is running.`); }
  };
  const selectedClass: DefectClass = item.detections.find((d) => d.id === selectedDetection)?.className ?? (item.defect === "None detected" ? "Unknown Anomaly" : item.defect);
  const explanation = item.mechanicalExplanation ?? mechanicalKnowledge[selectedClass];
  const currentLiveResult = liveResult;
  return <div className="aa-inspector-dark">
    <Header eyebrow="AI INSPECTION STUDIO" title="AI Inspection Studio" subtitle="Upload a brake image to check it for possible damage" action={<><label className="aa-part-select">Part<select value={item.id} onChange={(e) => { startingPartRef.current = e.target.value; setSelectedPart(e.target.value); setSelectedDetection(""); if (!liveResult) setDemoLoaded(true); }} aria-label="Select component">{selectableInspections.map((r) => <option key={r.id} value={r.id}>{r.id}</option>)}</select></label><Badge tone={currentLiveResult?.inference_mode === "real_ai" || (!currentLiveResult && backendOnline && inferenceMode === "real_ai") ? "passed" : currentLiveResult || (backendOnline && inferenceMode === "demo_mock") ? "neutral" : "demo"}>{currentLiveResult ? (currentLiveResult.inference_mode === "real_ai" ? "REAL YOLO AI" : "MOCK") : backendOnline ? (inferenceMode === "real_ai" ? "REAL YOLO AI READY" : "MOCK BACKEND READY") : "DEMO INSPECTION"}</Badge></>}/>
    <section className={`aa-primary-upload ${scanning ? "scanning" : ""}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (!scanning) chooseFile(event.dataTransfer.files?.[0]); }} aria-label="Upload an image for automatic YOLO inspection">
      <input ref={inputRef} type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" hidden onChange={(event) => { chooseFile(event.currentTarget.files?.[0]); event.currentTarget.value = ""; }}/>
      <span className="aa-primary-upload-icon">↑</span><div className="aa-primary-upload-copy"><b>{scanning ? "Checking your image…" : file ? file.name : "Upload a brake image"}</b><span>{scanning ? "YOLO is checking it now. Results will appear below." : fileMessage || "Drop an image here or choose a file. The check starts automatically."}</span><small>JPG, PNG, or WEBP · up to 15 MB</small></div>
      <div className="aa-primary-upload-actions"><button type="button" className="button button-primary aa-primary-upload-button" disabled={scanning} onClick={() => inputRef.current?.click()}>{file ? "Choose another image" : "Browse images"}</button>{file && <button type="button" className="button button-secondary aa-primary-clear-button" disabled={scanning} onClick={clearUpload}>Clear image</button>}</div>
    </section>
    <div className={`aa-inspector-grid ${full ? "fullscreen-image" : ""}`}><section className={`panel aa-inspector-image ${liveResult ? "has-live-result" : ""}`}><div className="panel-heading"><div><h2>Visual inspection</h2><p>{item.id} · {item.batchId}</p></div><button className="icon-button" onClick={() => setFull(!full)} aria-label={full ? "Exit fullscreen" : "Expand image"}>⛶</button></div>
      {preview ? liveResult ? <LiveImageComparison source={preview} annotatedSource={annotatedPreview} result={liveResult} selectedIndex={liveSelection} zoom={zoom} onSelect={setLiveSelection}/> : <div className="aa-rotor-stage" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); chooseFile(e.dataTransfer.files?.[0]); }}><Image unoptimized width={1200} height={1200} src={preview} alt={`Original uploaded image preview: ${file?.name}`} style={{ maxWidth: "100%", maxHeight: 440, width: "auto", height: "auto", objectFit: "contain", transform: `scale(${zoom})` }}/><div className="aa-image-caption"><span>{file?.name}</span><span>{scanning ? "YOLO inference in progress" : uploadError ? "Inspection unavailable" : "Original upload"}</span></div>{scanning && <div className="aa-scanning-overlay"><span className="aa-spinner"/>Running YOLOv8 Inspection...</div>}</div> : demoLoaded ? <div onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); chooseFile(e.dataTransfer.files?.[0]); }}><RotorIllustration zoom={zoom} overlays={{ boxes, masks, heatmap }} selectedDetection={selectedDetection} detections={item.detections} opacity={opacity}/></div> : <div className="aa-rotor-stage" style={{ minHeight: 300, display: "grid", placeItems: "center" }}>Drop a brake component image here, or choose a sample below.</div>}
      <div className="aa-viewer-toolbar"><span className="aa-muted">Try a sample</span>{([ ["crack", "Cracked rotor"], ["clean", "Clean rotor"], ["surface_defect", "Surface damage"] ] as const).map(([name, label]) => <button key={name} className="button button-secondary" disabled={scanning || !backendOnline} onClick={() => void loadSample(name)}>{label}</button>)}<button className="button button-secondary" disabled={scanning} onClick={() => { setFile(null); setAnnotatedPreview(""); setLiveResult(null); setDemoLoaded(true); setUploadError(""); setFileMessage("Example inspection loaded."); }}>Example inspection</button></div>
      {(uploadError || (!currentLiveResult && fileMessage) || !backendOnline) && <div className={uploadError ? "aa-caution" : "aa-muted"}>{uploadError || (!currentLiveResult && fileMessage) || (backendOnline ? "" : "Backend offline — showing example data")}</div>}
      <div className="aa-viewer-toolbar"><button onClick={() => setZoom(Math.max(.8, zoom - .1))} aria-label="Zoom out">−</button><span>{Math.round(zoom * 100)}%</span><button onClick={() => setZoom(Math.min(1.5, zoom + .1))} aria-label="Zoom in">+</button><button onClick={() => setZoom(1)}>Reset zoom</button><label>Overlay opacity <input type="range" min=".2" max="1" step=".05" value={opacity} onChange={(e) => setOpacity(Number(e.target.value))}/></label></div>
      {demoLoaded && <div className="aa-overlay-toggles"><label><input type="checkbox" checked={boxes} onChange={(e) => setBoxes(e.target.checked)}/> Bounding boxes</label><label><input type="checkbox" checked={masks} onChange={(e) => setMasks(e.target.checked)}/> Segmentation masks <Badge tone="demo">DEMO</Badge></label><label><input type="checkbox" checked={heatmap} onChange={(e) => setHeatmap(e.target.checked)}/> Anomaly heatmap <Badge tone="demo">DEMO</Badge></label></div>}
      {demoLoaded && <div className="aa-detections"><b>Detections ({item.detections.length})</b>{item.detections.length ? item.detections.map((d) => <button className={`aa-detection ${selectedDetection === d.id ? "active" : ""}`} key={d.id} title={`${(d.confidence * 100).toFixed(1)}% demonstration confidence`} onClick={() => { setSelectedDetection(d.id); setBoxes(true); }}><span className="severity-dot critical"/><span><strong>{item.review?.finalClass ?? d.className}</strong><small>{d.region} · {(d.confidence * 100).toFixed(0)}% confidence <em>Demo prediction</em></small></span><b>{d.severity}</b></button>) : <p className="aa-muted">No defects in this demo inspection.</p>}</div>}
    </section>
    {!currentLiveResult && <section className="panel aa-assessment"><details className="aa-detail-dropdown"><summary><span>More about this example</span><b>{demoLoaded ? `${explanation.defectClass} · suggested next step` : "Example inspection details"}</b><span className="aa-dropdown-chevron">⌄</span></summary><div className="aa-demo-tech-body">{demoLoaded ? <><h3>{explanation.defectClass}: what it is</h3><p>{explanation.whatItIs}</p><h3>How it may happen</h3><p>{explanation.principle}</p><h3>Possible causes</h3><ul>{explanation.possibleContributors.map((x) => <li key={x}>{x}</li>)}</ul><h3>Why it matters</h3><p>{explanation.potentialEffect}</p><div className="aa-rule"><div className="aa-rule-head"><strong>Suggested next step</strong><Badge tone="review">Engineering review</Badge></div><p>{explanation.suggestedAction}</p></div><div className="aa-caution">Example guidance only. It does not confirm the cause or prove the part is safe.</div><details className="aa-upload-log-detection"><summary>Measurement and rule details</summary><div className="aa-detail-dropdown-content"><p>{engineeringRule.id} · {engineeringRule.version}</p><p>{engineeringRule.description}</p><ul>{engineeringRule.evidence.map((e) => <li key={e}>{e}</li>)}</ul></div></details></> : <div className="aa-caution">This example has no image-specific analysis. Upload a brake image to run YOLO.</div>}</div></details></section>}
    {!currentLiveResult && <ProcessPanel item={item} navigate={navigate}/>}</div>
    {currentLiveResult && <LiveInspectionAnalysis result={currentLiveResult} selectedIndex={liveSelection} onSelect={setLiveSelection} navigate={navigate}/>}
    {!currentLiveResult && <div className="aa-inspector-bottom"><button className="button button-secondary" onClick={() => { navigate("Batch Quality Analytics"); const url = new URL(window.location.href); url.searchParams.set("batch", item.batchId); window.history.replaceState({}, "", url); }}>View batch analytics</button><button className="button button-primary" onClick={() => navigate("Human Review", item.id)}>Send component to Human Review</button></div>}
  </div>;
}

function ProcessPanel({ item, navigate }: { item: Inspection; navigate: Props["navigate"] }) {
  const machine = machines.find((m) => m.id === item.machine) ?? machines[3]; const outsideLimit = machine.telemetry.temperatureC > machine.telemetry.referenceLimitC;
  return <details className="panel aa-process aa-detail-dropdown aa-process-dropdown"><summary><span>Process data</span><b>{machine.id} · {machine.station}</b><span className="aa-dropdown-chevron">⌄</span></summary><div className="aa-detail-dropdown-content"><div className="aa-machine-highlight"><span className="aa-machine-icon">M</span><span><small>DEMO MACHINE</small><strong>{machine.station}</strong><b>Machine {machine.id} · {item.batchId}</b></span><Badge tone="review">Check</Badge></div><div className="aa-telemetry"><span>Temperature <b className={outsideLimit ? "hot" : ""}>{machine.telemetry.temperatureC.toFixed(1)}°C</b></span><span>Example limit <b>{machine.telemetry.referenceLimitC}°C</b></span><span>Pressure <b>{machine.telemetry.pressureBar.toFixed(1)} bar</b></span><span>Vibration <b>{machine.telemetry.vibrationMmS.toFixed(1)} mm/s RMS</b></span><span>Cycle time <b>{machine.telemetry.cycleSeconds} s</b></span></div><div className="aa-process-note"><strong>What this means</strong><p>{machine.id === "M-04" && outsideLimit ? "The example temperature is above its reference. This does not prove it caused the defect." : "No unusual process reading is shown in this example."}</p><span>Example data · not connected to the uploaded image</span></div><div className="aa-recommendation"><small>Suggested next step</small><p>Ask the quality team to review these process readings.</p><button className="text-link" onClick={() => { navigate("Fault Intelligence Board"); const url = new URL(window.location.href); url.searchParams.set("machine", machine.id); window.history.replaceState({}, "", url); }}>Open machine details →</button></div></div></details>;
}

function BatchAnalytics({ inspections, navigate, setSelectedPart }: Props) {
  const [batchId, setBatchId] = useState(demoBatches[0].id); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All"); const [files, setFiles] = useState<File[]>([]); const [uploadMessage, setUploadMessage] = useState(""); const inputRef = useRef<HTMLInputElement>(null); const [page, setPage] = useState(1);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("batch"); if (requested && demoBatches.some((item) => item.id === requested)) setBatchId(requested); }, []);
  const batch = demoBatches.find((b) => b.id === batchId)!; const batchRows = inspections.filter((r) => r.batchId === batchId); const allRows = batchRows.filter((r) => r.id.toLowerCase().includes(search.toLowerCase()) && (filter === "All" || r.defect === filter || r.review?.finalClass === filter || r.severity === filter));
  const pageSize = 10; const pages = Math.max(1, Math.ceil(allRows.length / pageSize)); const pageRows = allRows.slice((page - 1) * pageSize, page * pageSize);
  const counts = statusCounts(batchRows); const flaggedRate = batchRows.length ? (counts.REVIEW + counts.REJECT) / batchRows.length * 100 : 0; const distributions = defectCounts(batchRows);
  const onFiles = (list: FileList | null) => { if (!list) return; const valid = Array.from(list).filter((f) => f.type.startsWith("image/") && f.size < 15 * 1024 * 1024); setFiles(valid); setUploadMessage(valid.length === list.length ? "Selected for local preview only. No inference service is connected." : "Only image files under 15 MB are supported."); };
  const csv = `Part ID,Batch,Line,Defect,Severity,Result\n${allRows.map((r) => [r.id, r.batchId, r.line, r.review?.finalClass ?? r.defect, r.severity, r.review?.finalDisposition ?? r.status].join(",")).join("\n")}`;
  return <><Header eyebrow="BATCH ANALYTICS" title="Batch Quality Analytics" subtitle="Spot repeated findings and quality changes across production batches" action={<><label className="aa-part-select">Batch<select aria-label="Select batch" value={batchId} onChange={(e) => { setBatchId(e.target.value); setPage(1); const url = new URL(window.location.href); url.searchParams.set("batch", e.target.value); window.history.replaceState({}, "", url); }}>{demoBatches.map((b) => <option key={b.id}>{b.id}</option>)}</select></label><Badge tone="demo">DEMO DATA</Badge></>}/>
    <div className="stat-grid"><MiniStat title="TOTAL PARTS" value={batchRows.length.toString()} caption={`${batch.id} · demo records`}/><MiniStat title="PASSED" value={counts.PASS.toString()} caption={`${Math.round(counts.PASS / (batchRows.length || 1) * 100)}% of records`} tone="green"/><MiniStat title="NEEDS REVIEW" value={counts.REVIEW.toString()} caption="Current shared inspection records" tone="amber"/><MiniStat title="REJECTED" value={counts.REJECT.toString()} caption="Current shared inspection records" tone="violet"/></div>
    <div className="aa-batch-grid"><section className="panel aa-batch-upload"><div className="panel-heading"><div><h2>Inspect a batch</h2><p>Choose files for a local preview · inference integration pending</p></div></div><button className="aa-dropzone" onClick={() => inputRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); onFiles(e.dataTransfer.files); }}><span className="aa-upload-icon">↑</span><b>Drop inspection images here</b><small>or browse · PNG, JPG, WEBP · up to 15 MB each</small><input ref={inputRef} type="file" accept="image/*" multiple hidden onChange={(e) => onFiles(e.target.files)}/></button>{files.length > 0 && <div className="aa-file-list">{files.map((f) => <span key={`${f.name}-${f.size}`}>{f.name} · {(f.size / 1024 / 1024).toFixed(1)} MB</span>)}</div>}<div className="aa-upload-footer"><span>{uploadMessage || "No external model or backend is connected."}</span><div><button className="button button-secondary" disabled={!files.length} onClick={() => { setFiles([]); setUploadMessage(""); }}>Clear selection</button><button className="button button-primary" disabled>Inference unavailable</button></div></div></section>
      <section className="panel aa-spc-card"><div className="panel-heading"><div><h2>Batch signal</h2><p>Flagged-part share of demo records · not a certified defect rate</p></div><Badge tone="review">{flaggedRate.toFixed(1)}% flagged</Badge></div><div className="aa-signal-big">{flaggedRate.toFixed(1)} <span>percent flagged</span></div><p>Review and reject dispositions divided by the records available for this batch. This descriptive share is not a statistical control-limit result.</p><div className="aa-signal-bar"><span style={{ width: `${flaggedRate}%` }}/><i style={{ left: "12%" }}/></div><div className="aa-signal-legend"><span><i/> Current {flaggedRate.toFixed(1)}%</span><span><i/> Illustrative reference 12%</span></div><strong className="aa-signal-label">SPC status · Review signal only</strong></section></div>
    <div className="middle-grid"><section className="panel aa-defect-dist"><div className="panel-heading"><div><h2>Defect-class distribution</h2><p>Unique defect classes counted from current batch records</p></div></div>{distributions.map((d) => <div className="aa-distribution-row" key={d.defectClass}><span>{d.defectClass}</span><div><i style={{ width: `${d.percent}%` }}/></div><b>{d.percent.toFixed(1)}%</b><small>{d.count}</small></div>)}</section><section className="panel aa-batch-results"><div className="panel-heading"><div><h2>Batch outcomes</h2><p>{batchRows.length} demo records available for {batch.id}</p></div></div><div className="aa-outcome-bars"><span>Passed <i/><b>{counts.PASS}</b></span><span>Review <i/><b>{counts.REVIEW}</b></span><span>Rejected <i/><b>{counts.REJECT}</b></span></div><div className="aa-caution">Flagged share: {counts.REVIEW + counts.REJECT} / {batchRows.length} records = {flaggedRate.toFixed(1)}%. Flagged does not mean confirmed defective.</div></section></div>
    <section className="panel inspections-panel"><div className="panel-heading inspection-heading"><div><h2>Parts in {batchId}</h2><p>Search and open the linked component inspection</p></div><div className="inspection-actions"><label className="table-search"><span>⌕</span><input placeholder="Search Part ID" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}/></label><select className="aa-select" value={filter} onChange={(e) => { setFilter(e.target.value); setPage(1); }}><option>All</option>{[...classes, "Critical", "High", "Medium", "Low"].map((x) => <option key={x}>{x}</option>)}</select><button className="button button-secondary small-button" onClick={() => downloadCsv(csv, `${batchId}.csv`)}>↓ Export CSV</button></div></div><InspectionTable rows={pageRows} open={(id) => { setSelectedPart(id); navigate("AI Inspection Studio", id); }}/><div className="table-footer"><span>Showing {allRows.length ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, allRows.length)} of {allRows.length} demo records</span><span className="aa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><b>{page} / {pages}</b><button disabled={page >= pages} onClick={() => setPage(page + 1)}>Next</button></span></div></section>
  </>;
}

function MachineIntelligence({ inspections, navigate, setSelectedPart }: Props) {
  const [machineId, setMachineId] = useState("M-04");
  const [recordsPage, setRecordsPage] = useState(1);
  const [metric, setMetric] = useState<"temperatureC" | "pressureBar" | "vibrationMmS" | "cycleSeconds" | "rpm">("temperatureC");
  const [range, setRange] = useState(5);
  const machine = machines.find((m) => m.id === machineId)!;
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("machine"); if (requested && machines.some((item) => item.id === requested)) setMachineId(requested); }, []);
  const chooseMachine = (id: string) => { setMachineId(id); setRecordsPage(1); const url = new URL(window.location.href); url.searchParams.set("machine", id); window.history.replaceState({}, "", url); };
  const associated = inspections.filter((r) => r.machine === machine.id);
  const recordPageSize = 10; const recordPages = Math.max(1, Math.ceil(associated.length / recordPageSize)); const associatedPage = associated.slice((recordsPage - 1) * recordPageSize, recordsPage * recordPageSize);
  const trends = calculateFaultTrends(inspections, demoBatches);
  const trend = trends[0];
  const fastestIncreasing = [...trends].sort((a, b) => b.changePercentPoints - a.changePercentPoints)[0];
  const metricConfig = { temperatureC: ["Temperature", "°C"], pressureBar: ["Pressure", "bar"], vibrationMmS: ["Vibration", "mm/s RMS"], cycleSeconds: ["Cycle time", "s"], rpm: ["Spindle speed", "RPM"] } as const;
  const current = machine.telemetry[metric];
  const alerted = trends.filter((t) => t.direction === "Investigation Recommended" || t.direction === "Increasing");
  return <><Header eyebrow="FAULT INTELLIGENCE BOARD" title="Fault Intelligence Board" subtitle="Emerging defect patterns linked to inspection records and demonstration telemetry" action={<><label className="aa-part-select">Selected machine<select aria-label="Select machine" value={machineId} onChange={(e) => chooseMachine(e.target.value)}>{machines.map((m) => <option key={m.id}>{m.id}</option>)}</select></label><Badge tone="demo">DEMO DATA</Badge></>}/>
    <div className="stat-grid"><MiniStat title="FLAGGED RECORDS" value={String(inspections.filter((r) => r.status !== "PASS").length)} caption="Review + reject in shared fixture" tone="amber"/><MiniStat title="MOST FREQUENT CLASS" value={trend?.defectClass ?? "—"} caption={`${trend?.countsByBatch.at(-1)?.count ?? 0} in latest batch`} tone="blue"/><MiniStat title="FASTEST INCREASE" value={fastestIncreasing?.defectClass ?? "—"} caption={`${fastestIncreasing?.changePercentPoints.toFixed(1) ?? "0.0"} pp across latest batches`} tone="violet"/><MiniStat title="MACHINE UNDER REVIEW" value={machine.id} caption={`${associated.filter((r) => r.status !== "PASS").length} flagged linked records`} tone="amber"/></div>
    <div className="aa-machine-grid">{machines.map((m) => { const linked = inspections.filter((r) => r.machine === m.id); const flagged = linked.filter((r) => r.status !== "PASS").length; return <button key={m.id} className={`panel aa-machine-card ${m.id === machineId ? "active" : ""}`} onClick={() => chooseMachine(m.id)}><div className="aa-machine-card-top"><span className="aa-machine-icon">{m.id.slice(-2)}</span><Badge tone={m.status === "Operational" ? "passed" : "review"}>{m.status}</Badge></div><strong>Machine {m.id}</strong><span>{m.station}</span><div className="aa-machine-card-stats"><small>{linked.length} linked records <b>{flagged} flagged</b></small></div></button>; })}</div>
    <div className="aa-machine-detail-grid"><section className="panel aa-telemetry-panel"><div className="panel-heading"><div><h2>Emerging fault trends</h2><p>Counts and rates computed from demo inspection records</p></div><label>History<select className="aa-select" value={range} onChange={(e) => setRange(Number(e.target.value))}><option value={5}>5 batches</option></select></label></div>{trends.map((t) => <div className="aa-distribution-row" key={t.defectClass}><span>{t.defectClass}</span><div><i style={{ width: `${Math.min(100, t.countsByBatch.at(-1)?.ratePercent ?? 0) * 3}%` }}/></div><b>{(t.countsByBatch.at(-1)?.ratePercent ?? 0).toFixed(1)}%</b><small>{t.direction}</small></div>)}<p className="aa-muted">The displayed rates use inspected records per batch as the denominator. Pattern signals are descriptive and do not establish root cause.</p></section>
    <section className="panel aa-risk-panel"><div className="panel-heading"><div><h2>{machine.id} process telemetry</h2><p>Demonstration values · separate physical units</p></div><select className="aa-select" value={metric} onChange={(e) => setMetric(e.target.value as typeof metric)}>{Object.entries(metricConfig).map(([key, val]) => <option value={key} key={key}>{val[0]} ({val[1]})</option>)}</select></div><div className="aa-telemetry-current"><strong>{current.toFixed(1)} <small>{metricConfig[metric][1]}</small></strong><span>{metricConfig[metric][0]}</span></div><div className="aa-evidence"><b>Pattern alerts</b>{alerted.length ? alerted.map((t) => <span key={t.defectClass}>{t.direction}: {t.defectClass} changed {t.changePercentPoints.toFixed(1)} percentage points between the latest two batches; associated machine {t.machineId ?? "not available"}.</span>) : <span>No increasing defect trend in the current fixture.</span>}<span>Alerts summarize record associations; they do not prove machine causation.</span></div><div className="aa-recommendation"><small>OUTLOOK</small><p>Historical description only. Forecasting is not connected; review the affected records and confirm process evidence with manufacturing engineering.</p></div></section></div>
    <section className="panel aa-linked-parts"><div className="panel-heading"><div><h2>Linked inspection records</h2><p>{associated.length} records · {machine.id} · shared demonstration data</p></div></div><InspectionTable rows={associatedPage} open={(id) => { setSelectedPart(id); navigate("AI Inspection Studio", id); }}/><div className="table-footer"><span>Showing {associated.length ? (recordsPage - 1) * recordPageSize + 1 : 0}–{Math.min(recordsPage * recordPageSize, associated.length)} of {associated.length} linked records</span><span className="aa-pagination"><button disabled={recordsPage <= 1} onClick={() => setRecordsPage(recordsPage - 1)}>Previous</button><b>{recordsPage} / {recordPages}</b><button disabled={recordsPage >= recordPages} onClick={() => setRecordsPage(recordsPage + 1)}>Next</button></span></div></section>
  </>;
}

function HumanReview({ inspections, saveReview, setSelectedPart, navigate }: Props) {
  const queued = inspections.filter((r) => r.status === "REVIEW"); const completed = inspections.filter((r) => r.review && r.status !== "REVIEW"); const [selected, setSelected] = useState<Inspection | null>(null); const [defect, setDefect] = useState<DefectClass>("Surface Crack"); const [disposition, setDisposition] = useState<Disposition>("REVIEW"); const [notes, setNotes] = useState(""); const [reason, setReason] = useState(""); const [savedMessage, setSavedMessage] = useState("");
  const openReview = (row: Inspection) => { setSelected(row); setDefect(row.review?.finalClass ?? (row.defect === "None detected" ? "Unknown Anomaly" : row.defect)); setDisposition(row.review?.finalDisposition ?? row.status); setNotes(row.review?.notes ?? ""); setReason(row.review?.reason ?? ""); };
  const submit = () => { if (!selected || !reason.trim()) return; const originalDisposition = selected.review?.originalDisposition ?? selected.status; if (originalDisposition === "REJECT" && disposition === "PASS") { setSavedMessage("An authorized rejection approval workflow is required before PASS can be assigned."); return; } const review: InspectorReview = { reviewer: "Alex Rivera", timestamp: new Date().toISOString(), originalClass: selected.review?.originalClass ?? (selected.defect === "None detected" ? "Unknown Anomaly" : selected.defect), finalClass: defect, originalDisposition, finalDisposition: disposition, notes, reason }; saveReview(selected.id, review); setSelected(null); setSavedMessage(`${selected.id} review saved; original AI finding retained.`); window.setTimeout(() => setSavedMessage(""), 4500); };
  return <><Header eyebrow="HUMAN-IN-THE-LOOP" title="Human Review" subtitle="Engineer-owned decisions for uncertain or safety-critical findings" action={<Badge tone="review">{queued.length} in queue</Badge>}/><div className="aa-review-banner"><b>Human authority stays in control</b><span>Original model predictions remain in the audit trail. A rejected component cannot be changed to PASS in this prototype without an authorized approval workflow.</span></div><section className="panel inspections-panel"><div className="panel-heading inspection-heading"><div><h2>Review queue</h2><p>Open a record to inspect evidence and record an override</p></div></div>{queued.length ? <div className="table-scroll"><table><thead><tr><th>PART / BATCH</th><th>AI-PREDICTED DEFECT</th><th>SEVERITY</th><th>INITIAL DISPOSITION</th><th>REVIEW STATUS</th><th/></tr></thead><tbody>{queued.map((row) => <tr key={row.id}><td><div className="part-id"><span className="part-glyph">◉</span><span><b>{row.id}</b><small>{row.batchId}</small></span></div></td><td>{row.review ? `${row.review.originalClass} → ${row.review.finalClass}` : row.defect}</td><td>{row.severity}</td><td><Badge tone={row.status.toLowerCase()}>{row.review?.originalDisposition ?? row.status}</Badge></td><td>{row.review ? <Badge tone="passed">Reviewed · {row.review.reviewer}</Badge> : <Badge tone="review">Awaiting review</Badge>}</td><td><button className="text-link" onClick={() => openReview(row)}>{row.review ? "View / edit" : "Review part"} →</button></td></tr>)}</tbody></table></div> : <div className="empty-state">The review queue is clear.</div>}</section>{savedMessage && <div className="aa-inline-notice">{savedMessage}</div>}
    {completed.length > 0 && <section className="panel inspections-panel aa-completed-reviews"><div className="panel-heading inspection-heading"><div><h2>Completed reviews</h2><p>Corrections saved to the shared inspection records</p></div></div><div className="table-scroll"><table><thead><tr><th>PART</th><th>ORIGINAL MODEL CLASS</th><th>HUMAN DECISION</th><th>REVIEWER</th><th>TIME</th><th/></tr></thead><tbody>{completed.map((row) => <tr key={row.id}><td><b>{row.id}</b></td><td>{row.review?.originalClass}</td><td>{row.review?.finalClass} · {row.review?.finalDisposition}</td><td>{row.review?.reviewer}</td><td>{new Date(row.review!.timestamp).toLocaleString()}</td><td><button className="text-link" onClick={() => openReview(row)}>View review →</button></td></tr>)}</tbody></table></div></section>}
    {selected && <div className="aa-modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) setSelected(null); }}><section className="aa-review-modal" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="aa-modal-head"><div><span className="eyebrow">INSPECTOR OVERRIDE</span><h2 id="review-title">Review {selected.id}</h2></div><button className="icon-button" onClick={() => setSelected(null)} aria-label="Close review modal">×</button></div><div className="aa-modal-body"><div className="aa-modal-component"><div className="aa-modal-rotor">◉</div><span><b>{selected.batchId}</b><small>{selected.model}</small><Badge tone="demo">Image fixture · demo</Badge></span></div><div className="aa-ai-original"><small>ORIGINAL AI PREDICTION · RETAINED</small><b>{selected.review?.originalClass ?? selected.defect} · {Math.round(selected.confidence * 100)}% demo confidence</b><span>Initial disposition: {selected.review?.originalDisposition ?? selected.status}</span></div><label>Corrected defect class<select value={defect} onChange={(e) => setDefect(e.target.value as DefectClass)}>{classes.map((c) => <option key={c}>{c}</option>)}</select></label><label>Final disposition<select value={disposition} onChange={(e) => setDisposition(e.target.value as Disposition)}>{dispositions.map((d) => <option key={d}>{d}</option>)}</select></label><label>Reason for override <select value={reason} onChange={(e) => setReason(e.target.value)}><option value="">Select reason…</option><option>False positive</option><option>Defect class correction</option><option>Engineering assessment updated</option><option>Image quality limitation</option><option>Other</option></select></label><label>Inspector notes<textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Add concise engineering context"/></label><p className="aa-caution">A rejection cannot be overridden to PASS without an authorized approval workflow. This demo does not certify product safety.</p></div><div className="aa-modal-actions"><button className="button button-secondary" onClick={() => { setSelectedPart(selected.id); navigate("AI Inspection Studio", selected.id); setSelected(null); }}>Open inspection</button><button className="button button-secondary" onClick={() => setSelected(null)}>Cancel</button><button className="button button-primary" disabled={!reason.trim()} onClick={submit}>Save review</button></div></section></div>}
  </>;
}
