"use client";

import { useEffect, useRef, useState } from "react";
import { defectDistribution, demoBatches, engineeringRule, machines, productionLines, seedInspections } from "../../lib/mock-data";
import { statusCounts } from "../../lib/calculations";
import type { Disposition, DefectClass, Inspection, InspectorReview, ProductionLine } from "../../lib/types";

type ViewName = "Plant Overview" | "Component Inspector" | "Batch Analytics" | "Machine Intelligence" | "Human Review";
type Props = { view: ViewName; inspections: Inspection[]; selectedPart: string; setSelectedPart: (id: string) => void; navigate: (view: ViewName, partId?: string) => void; saveReview: (id: string, review: InspectorReview) => void };
const classes: DefectClass[] = ["Surface Crack", "Scratch", "Pitting", "Inclusion", "Casting Defect", "Unknown Anomaly"];
const dispositions: Disposition[] = ["PASS", "REVIEW", "REJECT"];

function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: string }) { return <span className={`aa-badge ${tone}`}>{children}</span>; }
function Header({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="aa-page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/>{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{action && <div className="aa-page-actions">{action}</div>}</div>; }
function MiniStat({ title, value, caption, tone = "blue" }: { title: string; value: string; caption: string; tone?: string }) { return <article className="stat-card aa-mini-stat"><div className="stat-top"><span>{title}</span><span className={`stat-icon ${tone}`}/></div><div className="stat-value">{value}</div><div className="stat-foot">{caption}</div></article>; }
function downloadCsv(text: string, name: string) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/csv;charset=utf-8" })); link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(link.href), 1000); }

export function AutoAuditView(props: Props) {
  if (props.view === "Component Inspector") return <Inspector {...props}/>;
  if (props.view === "Batch Analytics") return <BatchAnalytics {...props}/>;
  if (props.view === "Machine Intelligence") return <MachineIntelligence {...props}/>;
  if (props.view === "Human Review") return <HumanReview {...props}/>;
  return <Overview {...props}/>;
}

function Overview({ inspections, navigate, setSelectedPart }: Props) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("All"); const [severity, setSeverity] = useState("All"); const [line, setLine] = useState("All lines"); const [range, setRange] = useState("24 hours"); const [page, setPage] = useState(1);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("line"); if (requested && productionLines.some((item) => item.id === requested)) setLine(requested); }, []);
  const filtered = inspections.filter((item) => (item.id.toLowerCase().includes(search.toLowerCase())) && (status === "All" || item.status === status) && (severity === "All" || item.severity === severity) && (line === "All lines" || item.line.startsWith(line)));
  const perPage = 5; const pages = Math.max(1, Math.ceil(filtered.length / perPage)); const pageRows = filtered.slice((page - 1) * perPage, page * perPage);
  const lines: ProductionLine[] = productionLines;
  const open = (id: string) => { setSelectedPart(id); navigate("Component Inspector", id); };
  const csv = `Part ID,Batch ID,Line,Time,Defect,Severity,Result\n${filtered.map((r) => [r.id, r.batchId, r.line, r.time, r.review?.finalClass ?? r.defect, r.severity, r.review?.finalDisposition ?? r.status].join(",")).join("\n")}`;
  return <>
    <Header eyebrow="PLANT OVERVIEW" title="Plant Overview" subtitle="Real-time production quality and inspection intelligence" action={<><label className="aa-select-label">Plant North · 01<select aria-label="Production line filter" value={line} onChange={(e) => { setLine(e.target.value); setPage(1); const url = new URL(window.location.href); if (e.target.value === "All lines") url.searchParams.delete("line"); else url.searchParams.set("line", e.target.value); window.history.replaceState({}, "", url); }}><option>All lines</option><option>Line 01</option><option>Line 02</option><option>Line 03</option></select></label><select className="aa-select" value={range} onChange={(e) => setRange(e.target.value)} aria-label="Date range"><option>24 hours</option><option>7 days</option></select><Badge tone="demo">DEMO DATA</Badge><button className="button button-secondary" onClick={() => window.location.reload()}>↻ Refresh</button></>}/>
    <div className="stat-grid"><MiniStat title="INSPECTED PARTS" value="2,481" caption="Plant-level demo aggregate · 24h"/><MiniStat title="FIRST-PASS YIELD" value="98.6%" caption="Plant-level demo aggregate" tone="green"/><MiniStat title="NEEDS REVIEW" value="18" caption="Plant-level demo aggregate" tone="amber"/><MiniStat title="LINE AVAILABILITY" value="94.2%" caption="Plant-level demo aggregate" tone="violet"/></div>
    <div className="middle-grid"><section className="panel yield-panel"><div className="panel-heading"><div><h2>Production quality trend</h2><p>First-pass yield · illustrative demo series</p></div><select className="aa-select" value={range} onChange={(e) => setRange(e.target.value)}><option>24 hours</option><option>7 days</option></select></div><div className="aa-chart"><div className="aa-chart-axis"><span>100%</span><span>99%</span><span>98%</span><span>97%</span></div><svg viewBox="0 0 640 190" preserveAspectRatio="none" role="img" aria-label={`Illustrative first-pass yield over ${range}`}><title>Illustrative demo series · no live production measurements</title><path className="aa-chart-fill" d={range === "24 hours" ? "M0 145 C65 130 76 115 125 126 S204 82 259 97 S335 57 390 68 S465 36 512 49 S590 20 640 28 V190 H0Z" : "M0 153 C70 141 82 120 135 130 S208 99 260 112 S344 72 395 86 S468 53 523 62 S588 35 640 43 V190 H0Z"}/><path className="aa-chart-line" d={range === "24 hours" ? "M0 145 C65 130 76 115 125 126 S204 82 259 97 S335 57 390 68 S465 36 512 49 S590 20 640 28" : "M0 153 C70 141 82 120 135 130 S208 99 260 112 S344 72 395 86 S468 53 523 62 S588 35 640 43"}><title>Demo yield trend</title></path></svg><div className="aa-chart-labels"><span>{range === "24 hours" ? "06:00" : "Day 1"}</span><span>{range === "24 hours" ? "10:00" : "Day 2"}</span><span>{range === "24 hours" ? "14:00" : "Day 3"}</span><span>{range === "24 hours" ? "18:00" : "Day 4"}</span><span>{range === "24 hours" ? "22:00" : "Day 5"}</span></div></div></section>
      <section className="panel lines-panel"><div className="panel-heading"><div><h2>Production lines</h2><p>Current quality and output</p></div></div><div className="aa-overview-lines">{lines.map((item) => <button className="aa-overview-line" key={item.id} onClick={() => { setLine(item.id); setPage(1); const url = new URL(window.location.href); url.searchParams.set("line", item.id); window.history.replaceState({}, "", url); }}><span className="line-number blue">{item.id.slice(-2)}</span><span className="line-detail"><b>{item.id} — {item.name}</b><small>{item.inspected.toLocaleString()} inspected · {item.yield}% yield</small></span><Badge tone={item.status === "Operational" ? "passed" : "review"}>{item.status}</Badge></button>)}</div></section></div>
    <section className="panel inspections-panel"><div className="panel-heading inspection-heading"><div><h2>Recent inspections</h2><p>Open a component to see the complete engineering and process story</p></div><div className="inspection-actions"><label className="table-search"><span>⌕</span><input aria-label="Search part ID" placeholder="Search Part ID" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}/></label><select className="aa-select" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option>All</option>{dispositions.map((s) => <option key={s}>{s}</option>)}</select><select className="aa-select" value={severity} onChange={(e) => { setSeverity(e.target.value); setPage(1); }}><option>All</option>{["Critical", "High", "Medium", "Low", "None"].map((s) => <option key={s}>{s}</option>)}</select><button className="button button-secondary small-button" onClick={() => downloadCsv(csv, "autoaudit-inspections.csv")}>↓ Export</button></div></div><InspectionTable rows={pageRows} open={open}/><div className="table-footer"><span>Showing {filtered.length ? (page - 1) * perPage + 1 : 0}–{Math.min(page * perPage, filtered.length)} of {filtered.length} demo inspection records</span><span className="aa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><b>{page} / {pages}</b><button disabled={page >= pages} onClick={() => setPage(page + 1)}>Next</button></span></div></section>
  </>;
}

function InspectionTable({ rows, open }: { rows: Inspection[]; open: (id: string) => void }) {
  if (!rows.length) return <div className="empty-state">No inspections match these filters.</div>;
  return <div className="table-scroll"><table><thead><tr><th>PART / BATCH</th><th>PRODUCTION LINE</th><th>TIME</th><th>DEFECT CLASS</th><th>SEVERITY</th><th>RESULT</th><th/></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="part-id"><span className="part-glyph">◉</span><span><b>{row.id}</b><small>{row.batchId}</small></span></div></td><td>{row.line}</td><td className="mono">{row.time}</td><td>{row.review?.finalClass ?? row.defect}</td><td><Badge tone={row.severity === "Critical" || row.severity === "High" ? "failed" : row.severity === "Medium" ? "review" : "neutral"}>{row.severity}</Badge></td><td><Badge tone={row.status.toLowerCase()}>{row.review?.finalDisposition ?? row.status}</Badge></td><td><button className="text-link" onClick={() => open(row.id)}>Inspect image →</button></td></tr>)}</tbody></table></div>;
}

function RotorIllustration({ zoom, overlays, selectedDetection, detections, opacity }: { zoom: number; overlays: Record<string, boolean>; selectedDetection: string; detections: Inspection["detections"]; opacity: number }) {
  return <div className="aa-rotor-stage"><svg viewBox="0 0 640 440" role="img" aria-label="Illustrative brake disc inspection image with demonstration annotations" style={{ transform: `scale(${zoom})` }}>
    <defs><radialGradient id="rotor-metal"><stop offset="0" stopColor="#dce1e6"/><stop offset=".42" stopColor="#929ca6"/><stop offset=".58" stopColor="#e5e8ea"/><stop offset=".76" stopColor="#aab2b9"/><stop offset=".88" stopColor="#d8dde0"/><stop offset="1" stopColor="#727d86"/></radialGradient><radialGradient id="hub-metal"><stop offset="0" stopColor="#7f8992"/><stop offset=".7" stopColor="#c5cbd0"/><stop offset="1" stopColor="#737d86"/></radialGradient><filter id="shadow"><feGaussianBlur stdDeviation="8"/></filter><radialGradient id="heat"><stop stopColor="#ef5550" stopOpacity=".58"/><stop offset=".5" stopColor="#f4bd56" stopOpacity=".32"/><stop offset="1" stopColor="#f4bd56" stopOpacity="0"/></radialGradient></defs>
    <ellipse cx="320" cy="228" rx="226" ry="195" fill="#334256" opacity=".16" filter="url(#shadow)"/><g transform="rotate(-8 320 220)"><circle cx="320" cy="216" r="183" fill="url(#rotor-metal)" stroke="#697680" strokeWidth="3"/><circle cx="320" cy="216" r="155" fill="#69757e" stroke="#edf0f2" strokeWidth="2"/><circle cx="320" cy="216" r="138" fill="url(#rotor-metal)" stroke="#56636d" strokeWidth="2"/><circle cx="320" cy="216" r="92" fill="url(#hub-metal)" stroke="#59646e" strokeWidth="3"/><circle cx="320" cy="216" r="49" fill="#8e989f" stroke="#dfe3e6" strokeWidth="4"/><circle cx="320" cy="216" r="22" fill="#38434d" stroke="#d5dadd" strokeWidth="4"/>
    {Array.from({ length: 10 }, (_, i) => <g key={i} transform={`rotate(${i * 36} 320 216)`}><ellipse cx="320" cy="75" rx="7" ry="18" fill="#63707a" stroke="#e6e9ea" strokeWidth="2"/><ellipse cx="320" cy="118" rx="4" ry="10" fill="#515d67" opacity=".75"/><circle cx="320" cy="156" r="7" fill="#46515b" stroke="#e2e5e7" strokeWidth="2"/></g>)}
    <path d="M437 130 l-12 10 9 6 -16 13 4 10 -13 13 3 10" fill="none" stroke="#672d2b" strokeWidth="7" strokeLinecap="round" opacity=".88"/><path d="M437 130 l-12 10 9 6 -16 13 4 10 -13 13 3 10" fill="none" stroke="#d75d52" strokeWidth="3" strokeLinecap="round"/>
    {overlays.heatmap && <ellipse cx="420" cy="160" rx="92" ry="65" fill="url(#heat)" opacity={opacity}/>}
    {overlays.masks && <path d="M403 137 Q427 118 447 139 L439 157 427 164 432 180 413 197 406 177 414 161Z" fill="#eb6260" opacity={opacity * .46} stroke="#c64e49" strokeWidth="2"/>}
    {overlays.boxes && detections.map((d) => <g key={d.id} className={selectedDetection === d.id ? "is-selected" : ""}><rect x={d.bbox[0]} y={d.bbox[1]} width={d.bbox[2] - d.bbox[0]} height={d.bbox[3] - d.bbox[1]} fill="#e9544b" fillOpacity=".07" stroke="#d94e45" strokeWidth="3" strokeDasharray={selectedDetection === d.id ? "0" : "7 4"}/><rect x={d.bbox[0]} y={d.bbox[1] - 23} width="118" height="20" rx="4" fill="#263548"/><text x={d.bbox[0] + 7} y={d.bbox[1] - 9} fill="white" fontSize="10" fontWeight="600">{d.className} · {(d.confidence * 100).toFixed(0)}%</text></g>)}
    </g></svg><div className="aa-image-caption"><span>SVG illustration · demo annotations</span><span>Image-space only · no scale calibration</span></div></div>;
}

function Inspector({ inspections, selectedPart, setSelectedPart, navigate }: Props) {
  const item = inspections.find((r) => r.id === selectedPart) ?? inspections[0]; const [selectedDetection, setSelectedDetection] = useState(item.detections[0]?.id ?? ""); const [boxes, setBoxes] = useState(true); const [masks, setMasks] = useState(false); const [heatmap, setHeatmap] = useState(false); const [opacity, setOpacity] = useState(.65); const [zoom, setZoom] = useState(1); const [full, setFull] = useState(false);
  const severity = item.severity === "None" ? "No defect detected" : `${item.severity} — Provisional`;
  return <>
    <Header eyebrow="COMPONENT INSPECTOR" title="Component Inspector" subtitle="Image findings, engineering conformity, and process evidence · demonstration fixture" action={<><label className="aa-part-select">Part<select value={item.id} onChange={(e) => { setSelectedPart(e.target.value); setSelectedDetection(""); }} aria-label="Select component">{inspections.map((r) => <option key={r.id} value={r.id}>{r.id}</option>)}</select></label><Badge tone="demo">DEMO INSPECTION</Badge></>}/>
    <div className={`aa-inspector-grid ${full ? "fullscreen-image" : ""}`}><section className="panel aa-inspector-image"><div className="panel-heading"><div><h2>Visual inspection</h2><p>{item.id} · {item.batchId}</p></div><button className="icon-button" onClick={() => setFull(!full)} aria-label={full ? "Exit fullscreen" : "Expand image"}>⛶</button></div>
      <RotorIllustration zoom={zoom} overlays={{ boxes, masks, heatmap }} selectedDetection={selectedDetection} detections={item.detections} opacity={opacity}/>
      <div className="aa-viewer-toolbar"><button onClick={() => setZoom(Math.max(.8, zoom - .1))} aria-label="Zoom out">−</button><span>{Math.round(zoom * 100)}%</span><button onClick={() => setZoom(Math.min(1.5, zoom + .1))} aria-label="Zoom in">+</button><button onClick={() => setZoom(1)}>Reset zoom</button><label>Overlay opacity <input type="range" min=".2" max="1" step=".05" value={opacity} onChange={(e) => setOpacity(Number(e.target.value))}/></label></div>
      <div className="aa-overlay-toggles"><label><input type="checkbox" checked={boxes} onChange={(e) => setBoxes(e.target.checked)}/> Bounding boxes</label><label><input type="checkbox" checked={masks} onChange={(e) => setMasks(e.target.checked)}/> Segmentation masks <Badge tone="demo">DEMO</Badge></label><label><input type="checkbox" checked={heatmap} onChange={(e) => setHeatmap(e.target.checked)}/> Anomaly heatmap <Badge tone="demo">DEMO</Badge></label></div>
      <div className="aa-detections"><b>Detections ({item.detections.length})</b>{item.detections.length ? item.detections.map((d) => <button className={`aa-detection ${selectedDetection === d.id ? "active" : ""}`} key={d.id} title={`${(d.confidence * 100).toFixed(1)}% demonstration confidence; not a production prediction`} onClick={() => { setSelectedDetection(d.id); setBoxes(true); }}><span className="severity-dot critical"/><span><strong>{item.review?.finalClass ?? d.className}</strong><small>{d.region} · {(d.confidence * 100).toFixed(0)}% confidence <em>Demo prediction</em></small></span><b>{d.severity}</b></button>) : <p className="aa-muted">No defects in this demo inspection.</p>}</div>
    </section>
    <section className="panel aa-assessment"><div className="panel-heading"><div><h2>Engineering conformity</h2><p>Provisional assessment</p></div></div><div className={`aa-disposition ${item.status.toLowerCase()}`}><span>INSPECTION SEVERITY</span><strong>{severity}</strong><b>{item.review?.finalDisposition ?? item.status} / {item.status === "REJECT" ? "QUARANTINE" : item.status === "PASS" ? "RELEASE" : "ENGINEERING REVIEW"}</b><small>Disposition pending authorized engineering review</small></div><h3>Geometry measurements</h3><div className="aa-measure-list"><span>Defect area ratio <b>4.8% <i>demo</i></b></span><span>Crack length <b>148 px <i>image-space</i></b></span><span>Critical boundary intersection <b>True</b></span><span>Inspection region <b>{item.detections[0]?.region ?? "Friction track"}</b></span></div><div className="aa-rule"><div className="aa-rule-head"><strong>{engineeringRule.id}</strong><Badge tone="review">{engineeringRule.version}</Badge></div><p>{engineeringRule.description}</p><ul>{engineeringRule.evidence.map((e) => <li key={e}>{e}</li>)}</ul><div className="aa-rule-result"><span>DEMO RULE EVALUATION</span><b>{item.status === "PASS" ? "No configured rule triggered" : "Critical boundary condition flagged"}</b></div></div><div className="aa-caution">Computer vision alone cannot verify material integrity, internal porosity, or all structural properties. No certified physical measurement is available.</div></section>
    <ProcessPanel item={item} navigate={navigate}/></div>
    <div className="aa-inspector-bottom"><button className="button button-secondary" onClick={() => navigate("Batch Analytics")}>View batch analytics</button><button className="button button-primary" onClick={() => navigate("Human Review", item.id)}>Send component to Human Review</button></div>
  </>;
}

function ProcessPanel({ item, navigate }: { item: Inspection; navigate: Props["navigate"] }) {
  const machine = machines.find((m) => m.id === item.machine) ?? machines[3]; const outsideLimit = machine.telemetry.temperatureC > machine.telemetry.referenceLimitC;
  return <section className="panel aa-process"><div className="panel-heading"><div><h2>Process investigation</h2><p>Evidence linked to component history</p></div></div><div className="aa-machine-highlight"><span className="aa-machine-icon">M</span><span><small>STATION REQUIRES INVESTIGATION</small><strong>{machine.station}</strong><b>Machine {machine.id} · {item.batchId}</b></span><Badge tone="review">Investigate</Badge></div><div className="aa-telemetry"><span>Observed process temperature <b className={outsideLimit ? "hot" : ""}>{machine.telemetry.temperatureC.toFixed(1)}°C</b></span><span>Demo reference limit <b>{machine.telemetry.referenceLimitC}°C</b></span><span>Pressure <b>{machine.telemetry.pressureBar.toFixed(1)} bar</b></span><span>Vibration <b>{machine.telemetry.vibrationMmS.toFixed(1)} mm/s RMS</b></span><span>Cycle time <b>{machine.telemetry.cycleSeconds} s</b></span></div><div className="aa-process-note"><strong>Potential contributing factor</strong><p>Elevated process temperature at Station 03 may warrant investigation. Cause not yet confirmed; this is process evidence, not a causal finding.</p><span>Evidence status · Demonstration telemetry</span></div><div className="aa-recommendation"><small>RECOMMENDED ACTION</small><p>Inspect Machine M-04 thermal-control readings, validate the relevant process limits, and review affected batches before restarting the next production cycle.</p><button className="text-link" onClick={() => navigate("Machine Intelligence")}>Open machine investigation →</button></div></section>;
}

function BatchAnalytics({ inspections, navigate, setSelectedPart }: Props) {
  const [batchId, setBatchId] = useState(demoBatches[0].id); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All"); const [files, setFiles] = useState<File[]>([]); const [progress, setProgress] = useState(0); const [uploadMessage, setUploadMessage] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("batch"); if (requested && demoBatches.some((item) => item.id === requested)) setBatchId(requested); }, []);
  const batch = demoBatches.find((b) => b.id === batchId)!; const batchRows = inspections.filter((r) => r.batchId === batchId); const allRows = batchRows.filter((r) => r.id.toLowerCase().includes(search.toLowerCase()) && (filter === "All" || r.defect === filter || r.review?.finalClass === filter || r.severity === filter));
  const counts = statusCounts(batchRows); const baseline = statusCounts(seedInspections.filter((r) => r.batchId === batchId)); const adjustedCounts = { PASS: batch.passed + counts.PASS - baseline.PASS, REVIEW: batch.needsReview + counts.REVIEW - baseline.REVIEW, REJECT: batch.rejected + counts.REJECT - baseline.REJECT }; const flaggedRate = (adjustedCounts.REVIEW + adjustedCounts.REJECT) / batch.total * 100;
  const onFiles = (list: FileList | null) => { if (!list) return; const valid = Array.from(list).filter((f) => f.type.startsWith("image/") && f.size < 15 * 1024 * 1024); setFiles(valid); setProgress(0); setUploadMessage(valid.length === list.length ? `${valid.length} image${valid.length === 1 ? "" : "s"} ready for demo simulation` : "Only image files under 15 MB are supported."); };
  const simulate = () => { setProgress(5); setUploadMessage("Demo simulator running · no trained model connected"); let value = 5; const timer = window.setInterval(() => { value = Math.min(100, value + 19); setProgress(value); if (value >= 100) { window.clearInterval(timer); setUploadMessage("Demo processing complete · results are not model inferences"); } }, 220); };
  const csv = `Part ID,Batch,Line,Defect,Severity,Result\n${allRows.map((r) => [r.id, r.batchId, r.line, r.review?.finalClass ?? r.defect, r.severity, r.review?.finalDisposition ?? r.status].join(",")).join("\n")}`;
  return <><Header eyebrow="BATCH ANALYTICS" title="Batch Quality Analytics" subtitle="Spot repeated findings and quality changes across production batches" action={<><label className="aa-part-select">Batch<select aria-label="Select batch" value={batchId} onChange={(e) => { setBatchId(e.target.value); const url = new URL(window.location.href); url.searchParams.set("batch", e.target.value); window.history.replaceState({}, "", url); }}>{demoBatches.map((b) => <option key={b.id}>{b.id}</option>)}</select></label><Badge tone="demo">DEMO DATA</Badge></>}/>
    <div className="stat-grid"><MiniStat title="TOTAL PARTS" value={batch.total.toString()} caption={`${batch.id} · batch manifest`}/><MiniStat title="PASSED" value={adjustedCounts.PASS.toString()} caption={`${Math.round(adjustedCounts.PASS / batch.total * 100)}% of batch`} tone="green"/><MiniStat title="NEEDS REVIEW" value={adjustedCounts.REVIEW.toString()} caption="Manifest count adjusted for reviewed sample" tone="amber"/><MiniStat title="REJECTED" value={adjustedCounts.REJECT.toString()} caption="Manifest count adjusted for reviewed sample" tone="violet"/></div>
    <div className="aa-batch-grid"><section className="panel aa-batch-upload"><div className="panel-heading"><div><h2>Inspect a batch</h2><p>Upload brake-disc images for a clearly labeled demo simulation</p></div></div><button className="aa-dropzone" onClick={() => inputRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); onFiles(e.dataTransfer.files); }}><span className="aa-upload-icon">↑</span><b>Drop inspection images here</b><small>or browse · PNG, JPG, WEBP · up to 15 MB each</small><input ref={inputRef} type="file" accept="image/*" multiple hidden onChange={(e) => onFiles(e.target.files)}/></button>{files.length > 0 && <div className="aa-file-list">{files.map((f) => <span key={`${f.name}-${f.size}`}>{f.name} · {(f.size / 1024 / 1024).toFixed(1)} MB</span>)}</div>}{progress > 0 && <div className="aa-progress"><i style={{ width: `${progress}%` }}/></div>}<div className="aa-upload-footer"><span>{uploadMessage || "No external model or backend is connected."}</span><div><button className="button button-secondary" disabled={!files.length || progress > 0 && progress < 100} onClick={() => { setProgress(0); setUploadMessage("Simulation cancelled. Images remain selected."); }}>Cancel</button><button className="button button-primary" disabled={!files.length || progress > 0 && progress < 100} onClick={simulate}>{progress === 100 ? "Retry demo" : "Run demo inspection"}</button></div></div></section>
      <section className="panel aa-spc-card"><div className="panel-heading"><div><h2>Batch signal</h2><p>Flagged-part share of batch · not a certified defect rate</p></div><Badge tone="review">{flaggedRate.toFixed(1)}% flagged</Badge></div><div className="aa-signal-big">{flaggedRate >= 12 ? "+" : ""}{(flaggedRate - 12).toFixed(1)} <span>percentage points</span></div><p>Compared with the 7-day reference flagged-part share of 12.0%. This difference alone does not establish a statistical control-limit breach.</p><div className="aa-signal-bar"><span style={{ width: `${flaggedRate}%` }}/><i style={{ left: "12%" }}/></div><div className="aa-signal-legend"><span><i/> Current {flaggedRate.toFixed(1)}%</span><span><i/> Reference 12%</span></div><strong className="aa-signal-label">SPC status · Review signal only</strong></section></div>
    <div className="middle-grid"><section className="panel aa-defect-dist"><div className="panel-heading"><div><h2>Defect-class distribution</h2><p>Share of 20 categorized findings · illustrative batch sample</p></div></div>{defectDistribution.map((d) => <div className="aa-distribution-row" key={d.name}><span>{d.name}</span><div><i style={{ width: `${d.percent}%` }}/></div><b>{d.percent}%</b><small>{d.count}</small></div>)}</section><section className="panel aa-batch-results"><div className="panel-heading"><div><h2>Batch outcomes</h2><p>{counts.PASS + counts.REVIEW + counts.REJECT} demo records shown of {batch.total} manifest parts</p></div></div><div className="aa-outcome-bars"><span>Passed <i/><b>{counts.PASS}</b></span><span>Review <i/><b>{counts.REVIEW}</b></span><span>Rejected <i/><b>{counts.REJECT}</b></span></div><div className="aa-caution">Flagged share counts review + rejected units against this batch manifest: {adjustedCounts.REVIEW + adjustedCounts.REJECT} / {batch.total} = {flaggedRate.toFixed(1)}%. Flagged does not mean confirmed defective.</div></section></div>
    <section className="panel inspections-panel"><div className="panel-heading inspection-heading"><div><h2>Parts in {batchId}</h2><p>Search and open the linked component inspection</p></div><div className="inspection-actions"><label className="table-search"><span>⌕</span><input placeholder="Search Part ID" value={search} onChange={(e) => setSearch(e.target.value)}/></label><select className="aa-select" value={filter} onChange={(e) => setFilter(e.target.value)}><option>All</option>{[...classes, "Critical", "High", "Medium", "Low"].map((x) => <option key={x}>{x}</option>)}</select><button className="button button-secondary small-button" onClick={() => downloadCsv(csv, `${batchId}.csv`)}>↓ Export CSV</button></div></div><InspectionTable rows={allRows} open={(id) => { setSelectedPart(id); navigate("Component Inspector", id); }}/></section>
  </>;
}

function MachineIntelligence({ inspections, navigate, setSelectedPart }: Props) {
  const [machineId, setMachineId] = useState("M-04"); const [metric, setMetric] = useState<"temperatureC" | "pressureBar" | "vibrationMmS" | "cycleSeconds">("temperatureC"); const machine = machines.find((m) => m.id === machineId)!; const [tempOffset, setTempOffset] = useState(0); const [pressureOffset, setPressureOffset] = useState(0); const baseRisk = machine.id === "M-04" ? 72 : 24; const hypotheticalRisk = Math.max(5, Math.min(95, Math.round(baseRisk + tempOffset * 1.3 + pressureOffset * 1.7)));
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("machine"); if (requested && machines.some((item) => item.id === requested)) setMachineId(requested); }, []);
  const associated = inspections.filter((r) => r.machine === machine.id); const metricConfig = { temperatureC: ["Temperature", "°C", 150, 250], pressureBar: ["Pressure", "bar", 4, 9], vibrationMmS: ["Vibration", "mm/s RMS", 0, 5], cycleSeconds: ["Cycle time", "seconds", 0, 70] } as const; const selected = metricConfig[metric]; const current = machine.telemetry[metric];
  const chooseMachine = (id: string) => { setMachineId(id); const url = new URL(window.location.href); url.searchParams.set("machine", id); window.history.replaceState({}, "", url); };
  return <><Header eyebrow="MACHINE INTELLIGENCE" title="Machine Intelligence" subtitle="Investigate process evidence linked to inspection outcomes" action={<><label className="aa-part-select">Selected machine<select aria-label="Select machine" value={machineId} onChange={(e) => chooseMachine(e.target.value)}>{machines.map((m) => <option key={m.id}>{m.id}</option>)}</select></label><Badge tone="demo">SIMULATED RISK</Badge></>}/>
    <div className="aa-machine-grid">{machines.map((m) => <button key={m.id} className={`panel aa-machine-card ${m.id === machineId ? "active" : ""}`} onClick={() => chooseMachine(m.id)}><div className="aa-machine-card-top"><span className="aa-machine-icon">{m.id.slice(-2)}</span><Badge tone={m.status === "Operational" ? "passed" : "review"}>{m.status}</Badge></div><strong>Machine {m.id}</strong><span>{m.station}</span><div className="aa-machine-card-stats"><small>{m.recentParts} recent parts <b>{m.flaggedRate}% flagged</b></small></div></button>)}</div>
    <div className="aa-machine-detail-grid"><section className="panel aa-telemetry-panel"><div className="panel-heading"><div><h2>{machine.id} process telemetry</h2><p>Demo telemetry · separate units per metric</p></div><select className="aa-select" value={metric} onChange={(e) => setMetric(e.target.value as typeof metric)}>{Object.entries(metricConfig).map(([key, val]) => <option value={key} key={key}>{val[0]} ({val[1]})</option>)}</select></div><div className="aa-telemetry-current"><strong>{current.toFixed(1)} <small>{selected[1]}</small></strong><span>{selected[0]}</span>{metric === "temperatureC" && machine.id === "M-04" && <Badge tone="review">Above demo reference limit</Badge>}</div><div className="aa-telemetry-chart"><div className="aa-axis-labels">{[selected[3], selected[2] + (selected[3] - selected[2]) * 2 / 3, selected[2] + (selected[3] - selected[2]) / 3, selected[2]].map((value) => <span key={value}>{value.toFixed(0)}</span>)}</div><svg viewBox="0 0 600 140" preserveAspectRatio="none" role="img" aria-label={`${selected[0]} demonstration series in ${selected[1]}`}><title>Illustrative demonstration telemetry · not a live machine reading</title><path d="M0 110 C55 108 75 82 132 95 S209 53 268 72 S352 35 404 61 S483 20 533 46 S575 28 600 32"/></svg><label>{selected[2]} to {selected[3]} {selected[1]}</label></div><p className="aa-muted">Historical values are a demonstration series, not a live machine feed. Vibration is velocity RMS.</p></section>
    <section className="panel aa-risk-panel"><div className="panel-heading"><div><h2>Future-risk demonstration</h2><p>Not a validated forecasting model</p></div><Badge tone="demo">SIMULATED</Badge></div><div className="aa-risk-meter"><div className="aa-risk-ring" style={{ "--risk": `${machine.id === "M-04" ? 72 : 24}%` } as React.CSSProperties}><strong>{machine.id === "M-04" ? 72 : 24}<small>%</small></strong></div><span>{machine.id} estimated defect risk</span></div><p>This risk number is a scripted demonstration fixture. It is not an ML prediction and must not guide production decisions.</p><div className="aa-evidence"><b>Process evidence summary <Badge tone="demo">MOCK</Badge></b><span>1. Temperature above demo reference by {(machine.telemetry.temperatureC - machine.telemetry.referenceLimitC).toFixed(1)}°C</span><span>2. Flagged rate elevated in linked sample</span><span>3. Association is not proof of causation</span></div><div className="aa-what-if"><b>What-if simulator</b><label>Temperature offset <span>−20°C<input type="range" min="-20" max="20" value={tempOffset} onChange={(e) => setTempOffset(Number(e.target.value))}/>+20°C</span></label><label>Pressure offset <span>−1 bar<input type="range" min="-1" max="1" step=".1" value={pressureOffset} onChange={(e) => setPressureOffset(Number(e.target.value))}/>+1 bar</span></label><div>Hypothetical risk index <b>{hypotheticalRisk}%</b><small>Simulated calculation only</small></div></div></section></div>
    <section className="panel aa-linked-parts"><div className="panel-heading"><div><h2>Linked inspection records</h2><p>{associated.length} records in this demonstration sample · batch {associated[0]?.batchId ?? "—"}</p></div></div><InspectionTable rows={associated} open={(id) => { setSelectedPart(id); navigate("Component Inspector", id); }}/></section>
  </>;
}

function HumanReview({ inspections, saveReview, setSelectedPart, navigate }: Props) {
  const queued = inspections.filter((r) => r.status === "REVIEW"); const completed = inspections.filter((r) => r.review && r.status !== "REVIEW"); const [selected, setSelected] = useState<Inspection | null>(null); const [defect, setDefect] = useState<DefectClass>("Surface Crack"); const [disposition, setDisposition] = useState<Disposition>("REVIEW"); const [notes, setNotes] = useState(""); const [reason, setReason] = useState(""); const [savedMessage, setSavedMessage] = useState("");
  const openReview = (row: Inspection) => { setSelected(row); setDefect(row.review?.finalClass ?? (row.defect === "None detected" ? "Unknown Anomaly" : row.defect)); setDisposition(row.review?.finalDisposition ?? row.status); setNotes(row.review?.notes ?? ""); setReason(row.review?.reason ?? ""); };
  const submit = () => { if (!selected || !reason.trim()) return; const originalDisposition = selected.review?.originalDisposition ?? selected.status; if (originalDisposition === "REJECT" && disposition === "PASS") { setSavedMessage("An authorized rejection approval workflow is required before PASS can be assigned."); return; } const review: InspectorReview = { reviewer: "Alex Rivera", timestamp: new Date().toISOString(), originalClass: selected.review?.originalClass ?? (selected.defect === "None detected" ? "Unknown Anomaly" : selected.defect), finalClass: defect, originalDisposition, finalDisposition: disposition, notes, reason }; saveReview(selected.id, review); setSelected(null); setSavedMessage(`${selected.id} review saved; original AI finding retained.`); window.setTimeout(() => setSavedMessage(""), 4500); };
  return <><Header eyebrow="HUMAN-IN-THE-LOOP" title="Human Review" subtitle="Engineer-owned decisions for uncertain or safety-critical findings" action={<Badge tone="review">{queued.length} in queue</Badge>}/><div className="aa-review-banner"><b>Human authority stays in control</b><span>Original model predictions remain in the audit trail. A rejected component cannot be changed to PASS in this prototype without an authorized approval workflow.</span></div><section className="panel inspections-panel"><div className="panel-heading inspection-heading"><div><h2>Review queue</h2><p>Open a record to inspect evidence and record an override</p></div></div>{queued.length ? <div className="table-scroll"><table><thead><tr><th>PART / BATCH</th><th>AI-PREDICTED DEFECT</th><th>SEVERITY</th><th>INITIAL DISPOSITION</th><th>REVIEW STATUS</th><th/></tr></thead><tbody>{queued.map((row) => <tr key={row.id}><td><div className="part-id"><span className="part-glyph">◉</span><span><b>{row.id}</b><small>{row.batchId}</small></span></div></td><td>{row.review ? `${row.review.originalClass} → ${row.review.finalClass}` : row.defect}</td><td>{row.severity}</td><td><Badge tone={row.status.toLowerCase()}>{row.review?.originalDisposition ?? row.status}</Badge></td><td>{row.review ? <Badge tone="passed">Reviewed · {row.review.reviewer}</Badge> : <Badge tone="review">Awaiting review</Badge>}</td><td><button className="text-link" onClick={() => openReview(row)}>{row.review ? "View / edit" : "Review part"} →</button></td></tr>)}</tbody></table></div> : <div className="empty-state">The review queue is clear.</div>}</section>{savedMessage && <div className="aa-inline-notice">{savedMessage}</div>}
    {completed.length > 0 && <section className="panel inspections-panel aa-completed-reviews"><div className="panel-heading inspection-heading"><div><h2>Completed reviews</h2><p>Corrections saved to the shared inspection records</p></div></div><div className="table-scroll"><table><thead><tr><th>PART</th><th>ORIGINAL MODEL CLASS</th><th>HUMAN DECISION</th><th>REVIEWER</th><th>TIME</th><th/></tr></thead><tbody>{completed.map((row) => <tr key={row.id}><td><b>{row.id}</b></td><td>{row.review?.originalClass}</td><td>{row.review?.finalClass} · {row.review?.finalDisposition}</td><td>{row.review?.reviewer}</td><td>{new Date(row.review!.timestamp).toLocaleString()}</td><td><button className="text-link" onClick={() => openReview(row)}>View review →</button></td></tr>)}</tbody></table></div></section>}
    {selected && <div className="aa-modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) setSelected(null); }}><section className="aa-review-modal" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="aa-modal-head"><div><span className="eyebrow">INSPECTOR OVERRIDE</span><h2 id="review-title">Review {selected.id}</h2></div><button className="icon-button" onClick={() => setSelected(null)} aria-label="Close review modal">×</button></div><div className="aa-modal-body"><div className="aa-modal-component"><div className="aa-modal-rotor">◉</div><span><b>{selected.batchId}</b><small>{selected.model}</small><Badge tone="demo">Image fixture · demo</Badge></span></div><div className="aa-ai-original"><small>ORIGINAL AI PREDICTION · RETAINED</small><b>{selected.review?.originalClass ?? selected.defect} · {Math.round(selected.confidence * 100)}% demo confidence</b><span>Initial disposition: {selected.review?.originalDisposition ?? selected.status}</span></div><label>Corrected defect class<select value={defect} onChange={(e) => setDefect(e.target.value as DefectClass)}>{classes.map((c) => <option key={c}>{c}</option>)}</select></label><label>Final disposition<select value={disposition} onChange={(e) => setDisposition(e.target.value as Disposition)}>{dispositions.map((d) => <option key={d}>{d}</option>)}</select></label><label>Reason for override <select value={reason} onChange={(e) => setReason(e.target.value)}><option value="">Select reason…</option><option>False positive</option><option>Defect class correction</option><option>Engineering assessment updated</option><option>Image quality limitation</option><option>Other</option></select></label><label>Inspector notes<textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Add concise engineering context"/></label><p className="aa-caution">A rejection cannot be overridden to PASS without an authorized approval workflow. This demo does not certify product safety.</p></div><div className="aa-modal-actions"><button className="button button-secondary" onClick={() => { setSelectedPart(selected.id); navigate("Component Inspector", selected.id); setSelected(null); }}>Open inspection</button><button className="button button-secondary" onClick={() => setSelected(null)}>Cancel</button><button className="button button-primary" disabled={!reason.trim()} onClick={submit}>Save review</button></div></section></div>}
  </>;
}
