import type { DefectClass, MechanicalExplanation } from "./types";

export const mechanicalKnowledge: Record<DefectClass, MechanicalExplanation> = {
  "Surface Crack": {
    defectClass: "Surface Crack",
    whatItIs: "A crack is a material discontinuity that can propagate under applied stress.",
    principle: "Thermal gradients, residual stress, and geometric stress concentration may contribute to crack initiation when local stress exceeds the material’s resistance. This is a general mechanism, not a confirmed cause for this part.",
    possibleContributors: ["Nonuniform cooling", "Casting imperfections", "Residual machining stress", "Thermal-process variation"],
    potentialEffect: "Reduced structural integrity and possible crack growth under cyclic thermal and mechanical loading.",
    suggestedAction: "Quarantine the component and request additional engineering inspection.",
  },
  Scratch: {
    defectClass: "Scratch",
    whatItIs: "A scratch is a localized surface mark, commonly associated with contact or handling after machining.",
    principle: "Abrasive contact can remove or displace surface material. Depth, orientation, and location affect whether it acts as a stress raiser.",
    possibleContributors: ["Part-to-part contact", "Fixture or tool contact", "Debris during handling", "Surface finishing variation"],
    potentialEffect: "A shallow mark may be cosmetic; a deeper or sharp-edged mark can create a local stress concentration.",
    suggestedAction: "Measure depth using the approved inspection method and check handling or fixture contact points.",
  },
  Scoring: {
    defectClass: "Scoring",
    whatItIs: "Scoring is a set of directional grooves or marks on the friction track.",
    principle: "Repeated abrasive contact or a machining-tool condition can produce grooves; the profile and spacing help distinguish possible sources.",
    possibleContributors: ["Tool wear or chatter", "Abrasive contamination", "Fixture alignment", "Finishing-process variation"],
    potentialEffect: "Altered friction-track finish and possible uneven contact during service.",
    suggestedAction: "Compare groove direction and spacing with machining records and inspect the finishing tool.",
  },
  Pitting: {
    defectClass: "Pitting",
    whatItIs: "Pitting is a small cavity or group of cavities visible at the surface.",
    principle: "Localized material loss or a near-surface discontinuity can form a cavity. Surface imaging alone cannot determine its depth or internal structure.",
    possibleContributors: ["Casting porosity", "Inclusion pull-out", "Surface contamination", "Finishing variation"],
    potentialEffect: "A cluster or deeper cavity can affect local surface integrity and requires measurement against approved criteria.",
    suggestedAction: "Inspect pit depth and distribution and compare with the applicable engineering acceptance criteria.",
  },
  Inclusion: {
    defectClass: "Inclusion",
    whatItIs: "An inclusion is a foreign or compositionally distinct feature within the metal matrix.",
    principle: "A local material discontinuity can differ mechanically from the surrounding matrix. Surface vision cannot confirm composition or subsurface extent.",
    possibleContributors: ["Melt cleanliness variation", "Refractory or dross entrainment", "Pouring practice variation"],
    potentialEffect: "Depending on size and position, an inclusion can act as a local stress concentrator.",
    suggestedAction: "Request an appropriate material evaluation and review melt and pouring records; do not infer composition from this image.",
  },
  "Casting Defect": {
    defectClass: "Casting Defect",
    whatItIs: "A casting defect is a visible irregularity associated with metal filling, solidification, or cooling.",
    principle: "Flow and solidification conditions influence shrinkage, cold-shut, and surface discontinuity formation. A visual class is not a root-cause determination.",
    possibleContributors: ["Mold filling variation", "Solidification or cooling variation", "Mold condition", "Process temperature variation"],
    potentialEffect: "The significance depends on defect type, depth, and location relative to load-bearing regions.",
    suggestedAction: "Classify the morphology and review the relevant casting and cooling history with manufacturing engineering.",
  },
  "Machining Defect": {
    defectClass: "Machining Defect",
    whatItIs: "A machining defect is an unintended surface or geometric feature introduced during material removal.",
    principle: "Tool geometry, cutting forces, vibration, and fixturing influence the resulting profile and surface texture.",
    possibleContributors: ["Tool wear", "Spindle or fixture vibration", "Incorrect setup", "Feed or speed variation"],
    potentialEffect: "Dimensional or finish variation may affect assembly and friction-track behavior if acceptance limits are exceeded.",
    suggestedAction: "Check dimensional measurements, tool-life records, and machine setup before releasing the affected lot.",
  },
  "Unknown Anomaly": {
    defectClass: "Unknown Anomaly",
    whatItIs: "An unknown anomaly is a visual feature that does not yet fit a validated defect class.",
    principle: "Image evidence alone is insufficient to assign a mechanism or material condition.",
    possibleContributors: ["Lighting or imaging variation", "Surface condition", "Manufacturing variation", "Unrepresented defect type"],
    potentialEffect: "Unknown until the feature is reviewed and characterized.",
    suggestedAction: "Route the component for human characterization and retain the image with its traceability data.",
  },
  "Chipping / edge damage": {
    defectClass: "Chipping / edge damage",
    whatItIs: "A chipped area is a localized loss of material at an edge or surface boundary.",
    principle: "Impact or brittle fracture can remove a small fragment; geometry and material condition influence propagation risk.",
    possibleContributors: ["Handling impact", "Fixture contact", "Casting edge condition", "Machining exit condition"],
    potentialEffect: "An edge discontinuity may concentrate stress and can affect balance or fit depending on location and size.",
    suggestedAction: "Measure the affected region and review handling and fixture contact points before disposition.",
  },
};
